Ordering-Inc/Ordering-UI

src/components/AddressForm/index.js
src/components/AddressForm/styles.js
src/components/AddressList/index.js
src/components/AddressList/styles.js
src/components/BusinessController/index.js
src/components/BusinessController/styles.js
src/components/BusinessTypeFilter/index.js
src/components/BusinessesListing/index.js
src/components/BusinessesListing/styles.js
src/components/Home/index.js
src/components/HomeHero/index.js
src/components/HomeHero/styles.js
src/styles/Tabs/index.js
template/Pages/BusinessesList/index.js
template/router.js

Home & Business Listing Issues

---

src/components/ForgotPasswordForm/index.js
src/components/ForgotPasswordForm/styles.js
template/router.js

```JS
import ForgotPassword from './pages/ForgotPassword'
<ForgotPassword ordering={ordering}/>
```

ForgotPassword Fix

---

src/components/MyOrders/index.js
src/components/MyOrders/styles.js
src/components/UserProfileForm/index.js
src/components/UserProfileForm/styles.js
template/Pages/MyOrders/index.js
template/Pages/Profile/index.js
template/router.js

*update style and adding edit functionality
*handling errors
*Saved Places

UserProfile and MyOrders

---

src/components/ReviewOrder/index.js
src/components/ReviewOrder/styles.js
template/router.js

https://www.loom.com/share/b30a3d32eb4d4f97a5e7492c57707e0b
```JS
import {ReviewOrder} from '../ReviewOrder'
<ReviewOrder open order={order} />

Review order

---

src/components/BusinessBasicInformation/index.js
src/components/BusinessInformation/index.js
src/components/BusinessInformation/styles.js

https://www.loom.com/share/3741f78f9efc44ac8025aed3762648b8

[FIX] deleting modal of business information and adding in businessBasicInformation

---

src/components/UserProfileForm/index.js
src/components/UserProfileForm/styles.js

[FIX] issue of UserProfile Image

---

src/components/Cms/index.js
src/components/Cms/styles.js
template/Pages/Cms/index.js
template/router.js

https://www.loom.com/share/2749859621cd4626b6800c6e999567a7

[ADD] Cms component UI and page

---

src/components/AddressList/index.js
src/components/BusinessBasicInformation/styles.js
src/components/BusinessProductsCategories/index.js
src/components/BusinessProductsCategories/styles.js
src/components/BusinessProductsListing/index.js
src/components/BusinessProductsListing/styles.js
src/components/BusinessTypeFilter/index.js
src/components/BusinessTypeFilter/styles.js
src/components/Cart/index.js
src/components/CartPopover/index.js
src/components/Checkout/index.js
src/components/Checkout/styles.js
src/components/OrderDetails/index.js
src/components/ProductItemAccordion/index.js
src/components/ProductsListing/index.js
src/components/UserDetails/index.js
src/utils/index.js

✔️  <strong>improve loading checkout</strong>
✔️  <strong>improve responsive checkout</strong>
✔️  <strong>improve responsive business products listing</strong>
✔️  <strong>add link to redirect in checkout</strong>
✔️  <strong>improve design for categories filters</strong>
✔️  <strong>add loading skeleton for addressList</strong>
✔️   <strong>edit a product cart</strong>

Refactor, fix and improve some components

---

src/components/SignUpForm/styles.js
src/components/UserPopover/index.js

https://app.asana.com/0/home/1191220738319232/1197154819532793
https://www.loom.com/share/77668a1bdf9c47449a4dc7f4724055df
https://app.asana.com/0/home/1191220738319232/1197154819528788

[FIX] signup responsive and header popover close on click

---

src/components/ForgotPasswordForm/styles.js

[FIX] fix forgotpassword responsive

---

src/components/BusinessBasicInformation/index.js
src/components/BusinessProductsCategories/index.js
src/components/BusinessProductsCategories/styles.js

https://www.loom.com/share/8be171997f884723ae515e198a6ba1dd

[ADD] functionality responsive for productCategories

---

src/components/ProductItemAccordion/index.js
src/components/ProductItemAccordion/styles.js

validation to show caret when product has comments

---

template/components/Header/styles.js

Improve header margin

---

src/components/Checkout/index.js
template/Pages/Checkout/index.js

- If user type wrong url like: `/checkout/SOME_CHARACTERS`, a message and a button should appear to go to the checkout list

Redirect to checkout list when uuid doesn't exist

---

src/components/SingleProductCard/styles.js

Improve single product style when is sold out

---

src/components/SpinnerLoader/styles.js

Responsive for spinner loader

---

src/components/HomeHero/index.js

- The slogan previously had the font of the main title of the homehero

[FIX] font of Slogan

---

src/components/BusinessBasicInformation/index.js
src/components/BusinessInformation/index.js
src/components/BusinessInformation/styles.js
src/components/Modal/index.js

Improve design for Business Information 

---

src/components/MyOrders/index.js
src/components/MyOrders/styles.js

- I refactor code and improve google maps image

Refactor code and improve google maps image on My orders

---

src/components/BusinessProductsListing/index.js
src/components/BusinessesListing/index.js
src/components/SearchBar/index.js
src/styles/Inputs/index.js

- SearchBar of businessList and productsList now have a placeholder

Fix search

---

src/components/Cms/index.js
src/components/PageNotFound/index.js
template/Pages/Cms/index.js

- Using functional component of ordering-components CmsContent

[ADD] functional component to Cms

---

src/components/Cart/index.js
src/components/Checkout/index.js
src/components/Checkout/styles.js
template/Pages/Checkout/index.js

- When user has a cart without products, he can go to checkout and this behavior is wrong, because he can't know if this cart have products
- Now the user can know if cart has no products and he can go to store for add products

Improve checkout list validations when cart has no products

---

template/components/Footer/styles.js

[FIX] align of copy

---

template/router.js

- I add support for Mozilla, Chrome, Opera, Edge & Safari browsers

Improve scrollbar style

---

src/components/Checkout/index.js

- Fix messages error when user type a invalid cart or user doesn't carts

Checkout buttons redirect

---

src/components/BusinessProductsListing/index.js
template/Pages/BusinessProductsList/index.js

https://www.loom.com/share/04210ab89b8e497a9190ec41ac325827

Product Form issues

---

package-lock.json
src/components/BusinessProductsListing/index.js
src/components/MyOrders/index.js
src/components/ProductItemAccordion/index.js
template/Pages/MyOrders/index.js

Story: https://app.asana.com/0/319423429024482/1194283974947417
Video: https://d.pr/v/BbGYWL

Add reorder an order

---

src/components/Checkout/index.js
src/components/PaymentOptionCash/index.js
src/components/PaymentOptions/index.js

https://www.loom.com/share/f0fcb5cf9eac415f8d39d0677aeeafe8

[FIX] Checkout place button

---

src/components/AddressList/index.js
src/components/Modal/index.js
src/components/Modal/styles.js
src/components/OrderTypeSelectorHeader/index.js

[ADD] Order Types for addressForm and fix bug of select

---

src/components/BusinessBasicInformation/index.js
src/components/BusinessBasicInformation/styles.js
src/components/BusinessInformation/styles.js
src/components/BusinessProductsList/index.js
src/components/BusinessProductsListing/index.js
src/components/Modal/index.js
src/components/Modal/styles.js
src/components/ProductForm/index.js
src/components/ProductItemAccordion/index.js
src/components/SingleProductCard/index.js
src/components/SingleProductCard/styles.js
src/utils/ScrollToTop.js
template/Pages/BusinessProductsList/index.js
template/Pages/BusinessesList/index.js

https://www.loom.com/share/f2b4fa0ac2e149ef8f7aea17267dc973

Business fixes improvements

---

src/components/BusinessItemAccordion/index.js
src/components/Cart/index.js
src/components/CartPopover/index.js
src/components/Checkout/index.js
template/router.js

Checkout improvements

---

src/components/AddressList/index.js
src/components/AddressList/styles.js
src/components/ForgotPasswordForm/index.js
src/components/ForgotPasswordForm/styles.js
src/components/LoginForm/index.js
src/components/LoginForm/styles.js
src/components/SignUpForm/index.js
src/components/SignUpForm/styles.js
template/router.js

Sign up / Login / Forgot password improvements

---

src/components/LoginForm/index.js
src/components/LoginForm/styles.js
src/components/ProductForm/index.js

[FIX] login form in modal

---

src/components/NotNetworkConnectivity/index.js
template/app.js

Preload offline component

---

src/components/BusinessInformation/styles.js

Add background color to avoid transparent  business information modal 

---

src/components/BusinessItemAccordion/index.js

Open cart or business when user add product

---

src/components/SingleProductCard/styles.js

Revert style of sold out tag for products

---

src/components/AddressForm/index.js
src/components/BusinessInformation/index.js

Google maps re-render bug

---

src/components/BusinessItemAccordion/index.js
src/components/Cart/index.js
src/components/Checkout/index.js

https://www.loom.com/share/d72a76da6c5d44d48d85973fe34856c3

Open business popover when user adds products and has more than one cart

---

src/components/ProductForm/index.js
src/components/ProductForm/styles.js

Align increment-decrement buttons in product form

---

src/components/Cart/index.js

Change text when business is closed

---

src/components/AddressDetails/index.js
src/components/AddressDetails/styles.js
src/components/Checkout/index.js
src/components/Checkout/styles.js

Checkout fixes

---

src/components/BusinessBasicInformation/index.js
src/components/BusinessBasicInformation/styles.js
src/components/BusinessInformation/index.js
src/components/BusinessInformation/styles.js
src/components/ProductForm/index.js

[FIX] dummie of product form and align text of businessInformation

---

src/styles/Selects/index.js

Order context issues

---

src/components/AddressesPopover/index.js
src/components/BusinessBasicInformation/index.js
src/components/BusinessBasicInformation/styles.js
src/components/Header/index.js
src/components/Header/styles.js
src/components/MomentContent/index.js
src/components/MomentContent/styles.js
src/components/MomentControl/index.js
src/components/SpinnerLoader/index.js
template/app.js

Improve header responsive

---

index-template.js

Add environment variable to set this parameter on Sentry: https://d.pr/i/lEEjTD

Add environment value

---

src/components/FacebookLogin/index.js
src/components/FacebookLogin/styles.js
src/components/ForgotPasswordForm/styles.js
src/components/LoginForm/index.js
src/components/LoginForm/styles.js
src/components/SignUpForm/styles.js
src/styles/Buttons/index.js

[FIX] login/signup 

---

src/components/Header/index.js
src/components/Header/styles.js
src/components/LogoutButton/index.js
src/components/SidebarMenu/index.js
src/components/SidebarMenu/styles.js

https://www.loom.com/share/2eb62d69904b46a482b3b31c16b4d13a

Sidebar menu

---

src/components/Cart/index.js

Me tocó hacer esto porque se agregó una ruta nueva `/:store` y hay conflicto porque al parecer tambien la está tomando en cuenta.

Open cart when user is in checkout

---

package-lock.json
src/components/OrderDetails/index.js
src/components/OrderDetails/styles.js

Show business header orders details

---

package-lock.json
package.json
template/Pages/BusinessProductsList/index.js
template/Pages/BusinessesList/index.js
template/Pages/Checkout/index.js
template/Pages/Cms/index.js
template/Pages/Home/index.js
template/Pages/Login/index.js
template/Pages/MyOrders/index.js
template/Pages/OrderDetails/index.js
template/Pages/Profile/index.js
template/app.js
template/components/HelmetTags/index.js
template/helmetdata.json
template/pages/ForgotPassword/index.js
template/pages/SignUp/index.js

Implement React Helmet for SEO

---

src/components/BusinessProductsListing/index.js
src/components/FloatingButton/index.js
src/components/UpsellingPage/styles.js

https://www.loom.com/share/9fc3f2946a31408096ff2615a98a0571

[ADD] loading text for view order button

---

src/components/AutoScroll/index.js
src/components/AutoScroll/styles.js
src/components/BusinessInformation/index.js
src/components/BusinessInformation/styles.js
src/components/BusinessReviews/styles.js
src/components/MyOrders/index.js

https://www.loom.com/share/9428f56f3dfb4a558e818d902dadc8aa
https://www.loom.com/share/80d7be723e2e492ea14c442172d12d7c

Autoscroll for schedules and active orders

---

src/components/BusinessBasicInformation/index.js
src/components/BusinessBasicInformation/styles.js
src/components/BusinessInformation/index.js
src/components/BusinessInformation/styles.js

Business Information icons

---

src/components/AutoScroll/index.js
src/components/AutoScroll/styles.js
src/components/MyOrders/index.js
src/components/MyOrders/styles.js

Fix active orders

---

src/components/UpsellingPage/index.js
src/components/UpsellingPage/styles.js

ASANA Task: https://app.asana.com/0/0/1199127996918368/f
Mobile view: 
https://d.pr/i/9NPAdU
https://d.pr/i/j3IZV5
Tablet view:
https://d.pr/i/bMP32u
https://d.pr/i/3uv2Qo
Desktop view: 
https://d.pr/i/TrlqBO

Upselling visual improvements

---

src/components/BusinessBasicInformation/styles.js
src/components/SearchBar/styles.js

ASANA task: https://app.asana.com/0/0/1199127996918366/f
Business card: https://d.pr/i/SE1Rwx
Search Bar: https://d.pr/i/XcAR7e

Add margin & center businessBasicInfo, bg of search same as general bg

---

src/components/BusinessTypeFilter/styles.js

https://www.loom.com/share/7fccc6ae420f4dffa70f18c43844b93c

BusinessList

---

src/components/BusinessItemAccordion/index.js
src/components/Cart/index.js
src/components/CartContent/index.js

Example video: https://www.loom.com/share/517a7664add84226882194c8b1880ad2

Improve open cart when user add products

---

src/components/BusinessTypeFilter/index.js
src/components/Messages/styles.js

ASANA TASKs:
https://app.asana.com/0/0/1199127996918371/f
https://app.asana.com/0/0/1199127996918360/f
https://d.pr/i/3LvqPM
https://d.pr/v/cjiTkG

Fix avatar image show out canvas

---

src/components/OrderDetails/index.js
src/components/OrderDetails/styles.js

ASANA Task: https://app.asana.com/0/0/1199127996918369/f
Mobile: https://d.pr/i/aQ2h70
Tablet: https://d.pr/i/qictwp
Web: https://d.pr/i/M28glj
Big screens: https://d.pr/i/1Yt90u

Order details visual improvements

---

src/components/BusinessProductsList/index.js
src/components/BusinessProductsList/styles.js
src/components/BusinessProductsListing/index.js

https://www.loom.com/share/c3c10d2aa7814d86937fe048d37cd183

Business Page

---

src/components/NotNetworkConnectivity/index.js
src/components/NotNetworkConnectivity/styles.js

ASANA Task: https://app.asana.com/0/0/1199127996918372/f
Mobile: https://d.pr/i/hMKfpV
Web: https://d.pr/i/ixldjG

Manage size of offline image on mobile-web

---

src/components/SignUpForm/styles.js

ASANA Task: https://app.asana.com/0/0/1199127996918375/f
Web: https://d.pr/i/TRA6mx
App: https://d.pr/i/Gs0fpQ

align fb button with rest elements

---

src/styles/Inputs/index.js

Apply in general.
Only placeholder: https://d.pr/i/2ouYgF
With information: https://d.pr/i/bKdBkJ

Change general input style based on design

---

src/components/SearchBar/index.js

ASANA Task: https://app.asana.com/0/0/1199127996918374/f
Por favor revisar esto, por que al presionar enter se activa el Effect, no estoy seguro por qué pero al presionar dos veces enter se quedaba cargando, por lo cual al recibir el keyCode del enter corté la función. Probé y funciona pero no sé si sea la mejor solución.
Antes: https://d.pr/v/ycGV1l

Prevent receive enter to avoid unreceived change

---

src/components/Cart/index.js
src/components/Checkout/index.js
src/components/Checkout/styles.js
src/components/LanguageSelector/index.js
src/components/StripeRedirectForm/index.js
src/components/StripeRedirectForm/styles.js
src/components/UserDetails/index.js
src/components/UserDetails/styles.js
src/components/UserProfileForm/index.js
template/Pages/Checkout/index.js

- https://app.asana.com/0/1188675693896486/1199166654497870/f
- https://app.asana.com/0/1188675693896486/1199166654497873/f

Checkout page issues

---

src/components/Cart/index.js
src/components/OrderDetails/index.js
src/components/ReviewOrder/index.js

Add percentage sign for cart discounts

---

src/components/Cart/index.js
src/components/Checkout/index.js
src/components/LanguageSelector/index.js
template/Pages/Checkout/index.js

- https://app.asana.com/0/1188675693896486/1199166654497866/f
- https://app.asana.com/0/1188675693896486/1199166654497867/f

Validate checkout fields (coupon and driver tips)

---

src/components/BusinessProductsListing/index.js
src/components/Cart/index.js
src/components/Checkout/index.js
src/components/FloatingButton/styles.js

Add validation for cart minimum

---

package-lock.json
package.json
src/components/InputPhoneNumber/index.js
src/components/InputPhoneNumber/styles.js
src/components/UserDetails/index.js
src/components/UserDetails/styles.js
src/components/UserProfileForm/index.js
src/components/UserProfileForm/styles.js

Implement input phone number

---

src/components/BusinessBasicInformation/index.js
src/components/BusinessInformation/index.js
src/components/BusinessInformation/styles.js
src/components/BusinessProductsListing/index.js
src/components/BusinessProductsListing/styles.js
src/components/BusinessReviews/index.js

https://app.asana.com/0/1191220738645130/1199166654497829, https://app.asana.com/0/1191220738645130/1199166654497828,
https://app.asana.com/0/1191220738645130/1199166654497827,
https://app.asana.com/0/1191220738645130/1199166654497839,
https://app.asana.com/0/1191220738645130/1199166654497830,
https://app.asana.com/0/1191220738645130/1199166654497825
https://www.loom.com/share/ea329ebc508c484fbf4a1a828ad8ae20

BusinessPage

---

src/components/BusinessItemAccordion/index.js
src/components/CartContent/index.js
src/components/CartPopover/index.js

- Improve cart behavior when user add product in another window: https://app.asana.com/0/1188675693896486/1199226540685278/f
- Close cart popover when the user is in checkout page: https://app.asana.com/0/1188675693896486/1199223117978140/f

Solve some cart issues

---

src/components/AddressForm/index.js
src/components/AddressForm/styles.js
src/styles/Inputs/index.js

Without info: https://d.pr/i/Ef1cR9
With info: https://d.pr/i/vRHpWB

Address form styles colors

---

src/components/AddressForm/styles.js

Now the icons fills with the main color: https://d.pr/i/fRlvIX

Change color to theme main and fill the icon too

---

src/components/BusinessInformation/index.js
src/components/BusinessProductsList/index.js
src/components/BusinessProductsListing/index.js

https://www.loom.com/share/7c8a69207c98466e99d222b2daf28db9

Products not found

---

src/components/AddressForm/styles.js
src/components/ProductForm/styles.js

Input color 

---

src/components/Modal/styles.js
src/components/ProductShare/styles.js

https://app.asana.com/0/1191220738645130/1199225014209368
https://www.loom.com/share/8125c50eb65d410189171d5b000353c1

[ADD] position fixed to icon close and share

---

src/components/Checkout/index.js

https://app.asana.com/0/1191220738645130/1199226540685286

[FIX] zoom of map

---

src/components/Cart/index.js

Tax value 

---

src/components/AutoScroll/index.js
src/components/OrdersOption/index.js
src/components/OrdersOption/styles.js

https://www.loom.com/share/faeece2adb5d4144aa9acbca4f7abae1

Autoscroll and margin for active orders

---

src/components/AddressForm/index.js

[FIX] autocomplete for address form

---

src/components/SignUpForm/index.js
src/components/SignUpForm/styles.js
src/components/UserDetails/index.js
src/components/UserProfileForm/index.js

Add input phone number for signup page

---

src/components/BusinessProductsListing/index.js
src/components/SearchBar/index.js

https://www.loom.com/share/01f391752aba45eda1b33603aa05017b
https://www.loom.com/share/c331f8b8d6b94be682514092d58e0e33

[FIX] time of search for business without lazyLoad

---

src/components/BusinessProductsList/index.js

https://www.loom.com/share/04ec010452e546e8b51defc94300daa5

[FIX] featured category when has not products

---

src/components/AddressList/index.js
src/components/BusinessItemAccordion/index.js
src/components/Cart/index.js
src/components/Checkout/index.js
src/components/Modal/index.js
src/components/ProductForm/index.js
src/components/ProductForm/styles.js
src/components/SignUpForm/index.js
src/components/SingleProductCard/index.js

Cart fixes and improvements

---

src/components/AddressDetails/index.js
src/components/AddressForm/index.js
src/components/AddressList/index.js
src/components/AddressList/styles.js
src/components/BusinessProductsListing/index.js
src/components/LanguageSelector/index.js
src/components/OrderTypeSelectorHeader/index.js
src/styles/Select/index.js

Address issues

---

src/components/AddressForm/index.js
src/components/AddressForm/styles.js

https://www.loom.com/share/7fe5cc6a58354b50b49de282d63798b8

[FEAT] marker of the map for change location when drag

---

src/components/OrderDetails/index.js
src/components/OrderDetails/styles.js

https://www.loom.com/share/29a935a6ca294a64b2a6b123d8a37b3e

Driver issues on order details

---

template/Pages/Home/index.js
template/Pages/Home/styles.js

https://www.loom.com/share/c72d6512150846fe848e74088a2dd621
https://www.loom.com/share/8abdded89ac547f6a8f1a6bca100ac82

[ADD] home content to project

---

src/components/AddressForm/styles.js
src/components/BusinessProductsListing/index.js
src/components/ProductForm/index.js
src/components/ProductForm/styles.js
src/components/ProductShare/styles.js
src/styles/Inputs/index.js

https://www.loom.com/share/edf9f9774cf74463b00295cbdf969af9
https://www.loom.com/share/f2b08b26f3854473ab8c9907e2824923

Product Form improvements

---

src/components/InputPhoneNumber/index.js
src/components/UserDetails/index.js

- When an user hasn't countryCode in your phone number, the input phone number component crashed

Improve input phone number

---

src/components/AutoScroll/styles.js
src/components/BusinessInformation/styles.js

https://www.loom.com/share/9ea79d988f354d88affd3fd3baf59ecc

[FIX] modal autoscroll rtl

---

src/components/HomeHero/index.js
src/components/HomeHero/styles.js

https://www.loom.com/share/5b07fc777c56484387c96bf5239647d4

Fix Home address input

---

src/components/AddressForm/index.js
src/components/AddressForm/styles.js
src/components/AddressList/index.js
src/components/BusinessProductsListing/index.js
src/components/Modal/index.js

- https://app.asana.com/0/1188675693896486/1199510513097768/f
- https://app.asana.com/0/1188675693896486/1199510513097767/f
https://www.loom.com/share/d927bfcc542f4ca5b4bc8ab9d120a0d2

Address form / address issues

---

src/components/AddressForm/index.js

AddressForm Input autocomplete

---

src/components/BusinessController/index.js
src/components/Dropdown/index.js
src/components/Messages/index.js
src/components/OrderDetails/index.js
src/components/ReviewOrder/index.js
src/components/SingleProductCard/index.js

Sentry issues

---

index.js
src/components/ResetPassword/index.js
src/components/ResetPassword/styles.js
src/components/SignUpForm/index.js
src/index.js
src/styles/Buttons/index.js
template/Pages/PagesList/index.js
template/Pages/ResetPassword/index.js
template/app.js
template/components/ListenPageChanges/index.js
template/helmetdata.json

https://www.loom.com/share/ca24f61c0f2c428486aad1014a947db5

Reset password

---

src/components/UserProfileForm/index.js

[FIX] errors when not image

---

src/components/ActiveOrders/index.js
src/components/ActiveOrders/styles.js
src/components/AutoScroll/index.js
src/components/MyOrders/index.js
src/components/OrdersOption/styles.js
src/components/UserProfileForm/ProfileOptions/index.js
src/components/UserProfileForm/index.js

https://www.loom.com/share/125d54cc08474fd98f58a9910419658a

Orders responsive

---

src/components/Header/index.js

[FIX] orderType responsive

---

src/components/OrderDetails/index.js
src/components/OrderDetails/styles.js

Improve order details style

---

src/components/GoogleGpsButton/styles.js
src/components/HomeHero/styles.js

rtl of address input

---

src/components/Cart/index.js
src/components/UpsellingPage/index.js

[FIX] padding of product form for upseling and cart

---

src/components/PreviousOrders/index.js

Reorder loading

---

src/components/ActiveOrders/index.js
src/components/ActiveOrders/styles.js
src/components/AddressForm/styles.js
src/components/AddressList/styles.js
src/components/BusinessInformation/styles.js
src/components/Confirm/index.js
src/components/OrderDetails/styles.js
src/components/OrderTypeSelectorHeader/index.js
src/components/OrderTypeSelectorHeader/styles.js
src/components/OrdersOption/styles.js
src/components/UserProfileForm/styles.js
src/styles/Buttons/index.js
src/utils/index.js

Rtl fixes and overflow improvements

---

src/components/UserProfileForm/styles.js

Fix container of user data

---

src/components/BusinessProductsListing/index.js
src/components/Cart/index.js
src/components/Cart/styles.js
src/components/Checkout/index.js
src/components/FloatingButton/index.js

Add message to explain minimum purchase in cart

---

src/components/AutoScroll/styles.js
src/components/BusinessInformation/styles.js

https://www.loom.com/share/83210e3cb1d4489e893dc2229121e27c

Autoscroll size

---

src/components/HomeHero/index.js
src/components/OrderDetails/index.js
src/components/ProductForm/index.js
src/components/ProductForm/styles.js
src/components/ProductOptionSubOption/styles.js
template/Pages/OrderDetails/index.js

- Product Form: https://app.asana.com/0/1188675693896486/1199635311070143
- Home: https://app.asana.com/0/1188675693896486/1199635311070141
- Order details: https://app.asana.com/0/1188675693896486/1199636504666189

Improve UX

---

src/components/BusinessProductsListing/index.js
src/components/Cms/index.js
src/components/NotFoundSource/index.js
src/components/OrderDetails/index.js
src/components/UserPopover/index.js
src/components/UserPopover/styles.js

https://d.pr/i/3a937a
https://d.pr/i/ct1u4g

Improve active tab in user popover

---

src/components/AddressList/index.js
src/components/BusinessProductsListing/index.js
src/components/Checkout/index.js
src/components/Messages/index.js
src/components/PaymentOptionStripe/index.js
src/components/PaymentOptions/index.js
src/components/ProductForm/index.js
src/components/UserProfileForm/index.js

[FIX] cannot read prop message of undefined

---

src/components/ResetPassword/index.js
template/Pages/ResetPassword/index.js
template/app.js
template/components/ListenPageChanges/index.js

Fix url of resetPassword

---

src/components/ProductOptionSubOption/index.js
src/components/ProductOptionSubOption/styles.js

[FIX] rtl of max limit error

---

src/components/BusinessProductsListing/index.js
src/components/BusinessesListing/index.js

Hide undefined error when other error appears

---

template/app.js

Add analytics component

---

template/app.js

Example: https://d.pr/i/MsuAas

Add validation for front version config

---

src/components/OrderTypeSelectorHeader/index.js

Fix order type selected by default

---

src/components/UserProfileForm/index.js

https://www.loom.com/share/63bee33026654134879812832da0dcca

User profile fix

---

src/components/AddressForm/index.js
src/components/AddressForm/styles.js
src/components/Cart/index.js
src/components/CartContent/index.js
src/components/Checkout/index.js
src/components/SignUpForm/index.js
src/components/UserDetails/index.js
src/components/UserFormDetails/index.js
src/components/UserProfileForm/index.js

UseValidationContext for Cart

---

src/components/OrderDetails/index.js

Order details delivery date time utc

---

src/components/Messages/index.js

[FIX] upload the same image file twice in a row

---

src/components/SearchBar/index.js

https://www.loom.com/share/09f3de404ae34f2ebbde921377bb6c42

Fix business search when press special keys

---

src/components/ResetPassword/index.js

Improve changed password message alert

---

src/components/UserFormDetails/index.js

https://www.loom.com/share/e653cf8f15854c3d840ab523058e1ac6
https://www.loom.com/share/73561b29f49f4aef887c23058d4c6967
https://www.loom.com/share/0d4b331126ce41c7aec69d645274a4af

[FIX] update input when alert is triggered

---

src/components/Checkout/index.js
src/components/UserFormDetails/index.js
src/components/UserFormDetails/styles.js

delete password input on checkout page

---

src/components/ActiveOrders/index.js
src/components/PreviousOrders/index.js

[ADD] delivery datetime utc for orders

---

src/components/AutoScroll/index.js

https://www.loom.com/share/30389df6ac7542bea23a0b8a38fa47ad

[FIX] autoscroll bug

---

src/components/Dropdown/style.js
src/components/Image/index.js
src/components/UserProfileForm/styles.js

[FIX] aspect-ratio for userPopover image

---

src/components/OrderDetails/index.js

[ADD] tax included message for orderDetails

---

src/components/AddressForm/index.js

[FIX] address form text errors hardcoded

---

src/components/ActiveOrders/index.js
src/components/ActiveOrders/styles.js
src/components/OrdersOption/styles.js

bug: https://www.loom.com/share/ec3c3f5571b7482e8fbfc8aa025eab97?focus_title=1&muted=1&from_recorder=1
fix:

Active orders improvements

---

src/components/ActiveOrders/index.js
src/components/ActiveOrders/styles.js

[FIX] card height when map don't load succesfully

---

src/components/Cart/index.js

[FIX] cart minimum button when is undefined

---

src/components/SignUpForm/index.js

Signup fields

---

template/Pages/Checkout/index.js

stripe connect fixes

---

src/components/ActiveOrders/styles.js

[ADD] margin left for status order

---

src/components/Checkout/index.js
src/components/UserDetails/index.js
src/components/UserDetails/styles.js
src/utils/index.js

Improve checkout fields and userData design

---

src/components/ActiveOrders/index.js
src/components/OrderDetails/index.js

[ADD] summary for orderDetails and activeOrders

---

src/utils/index.js

[FIX] lang for business closed

---

src/components/UpsellingPage/index.js

Checkout issue

---

.vscode/settings.json
index-template.js
src/components/Messages/index.js
src/components/Messages/styles.js

Messages see

---

src/components/LoginForm/index.js
src/components/LoginForm/styles.js

[ADD] password see option

---

src/components/Messages/index.js
src/components/OrderDetails/index.js
src/components/OrderDetails/styles.js

Messages notifications

---

src/components/BusinessesListing/index.js
src/components/BusinessesListing/styles.js
src/components/HorizontalOrdersLayout/index.js
src/components/HorizontalOrdersLayout/styles.js
src/components/OrdersOption/index.js
src/components/OrdersOption/styles.js
src/components/SearchBar/index.js
src/components/SearchBar/styles.js
src/components/VerticalOrdersLayout/index.js
template/pages/MyOrders/index.js

Business list carts

---

src/components/ProductItemAccordion/index.js
src/components/ProductItemAccordion/styles.js

[FIX] arrow style for all navigators

---

src/components/MomentControl/index.js
src/components/MomentControl/styles.js

Reverts Ordering-Inc/Ordering-UI#421

Revert "[FIX] disabled hours when orderState is loading"

---

src/components/AddressForm/index.js
src/components/MomentContent/index.js
src/components/OrderDetails/index.js
src/components/OrderTypeSelectorHeader/index.js

✓ **MomentContent/index.js** - parse to int in case max_days_preorder is string
✓ **AddressForm/index.js** - show the max limit location value on error ERROR_MAX_LIMIT_LOCATION
✓ **OrderTypeSelectorHeader/index.js** - Set default type in case db config default is disabled.
✓ **OrderDetails/index.js** - Add validation in case guest_uudid_access.value is string

Improvements react settings

---

src/components/HorizontalOrdersLayout/styles.js

Story: https://app.asana.com/0/home/1191220738319232/1200102810566453
Demo: https://d.pr/v/97o2VQ
photos: https://d.pr/i/VZmb1R, https://d.pr/i/v353r0

[FIX] previousOrders size for callCenter

---

template/pages/BusinessesList/index.js

[ADD] props menus for business fetch

---

src/components/BusinessBasicInformation/index.js
src/components/BusinessController/index.js
src/components/BusinessTypeFilter/index.js

[FIX] traduction for business categories

---

src/components/AddressList/index.js
src/components/AddressList/styles.js
src/components/BusinessesMap/index.js
src/components/BusinessesMap/styles.js
src/components/Checkout/index.js
src/components/PhoneAutocomplete/index.js
src/components/PhoneAutocomplete/styles.js

Demo button continueWith: https://d.pr/v/EL7ux3

Call center3

---

src/components/AddressList/index.js
src/components/Header/index.js
src/components/PhoneAutocomplete/index.js

Stories: https://app.asana.com/0/1191220738645130/1200207939183597, https://app.asana.com/0/1191220738645130/1200209739051759

Call center4

---

src/components/ForgotPasswordForm/index.js
src/components/LoginForm/index.js
src/components/SignUpForm/index.js
src/components/UserFormDetails/index.js

The field no longer allows the following characters: &,()%";:ç?<>{}\[]

[ADD] not allowed some characters for email input

---

src/themes/two/src/components/Header/index.js

Story: https://app.asana.com/0/home/1191220738319232/1200227593157545
Demo: https://d.pr/i/l4M6yc

BusinessPage Issues (DoorDash)

---

src/themes/two/src/components/Header/index.js

Story: https://app.asana.com/0/home/1191220738319232/1200227593157541
Demo: https://d.pr/v/yVqXFY

Other Issues (DoorDash)

---

src/themes/two/src/components/ProductItemAccordion/styles.js

cart Issues (Doordash)

---

src/themes/two/src/components/AddressList/index.js
src/themes/two/src/components/Header/index.js
src/themes/two/src/components/Header/styles.js
src/themes/two/src/components/MomentPopover/index.js
src/themes/two/src/components/MomentPopover/styles.js
src/themes/two/src/components/SidebarMenu/index.js
src/themes/two/src/components/SidebarMenu/styles.js
src/themes/two/src/components/SignUpForm/index.js

Story: https://app.asana.com/0/home/1191220738319232/1200227593157467, https://app.asana.com/0/home/1191220738319232/1200227593157468,
https://app.asana.com/0/1191220738645130/1200227593157470
Demo: https://d.pr/v/8ZFN7K
New Demo: https://d.pr/v/tMtJHS

Signup issues (DoorDash)

---

src/themes/two/src/components/PaymentOptionStripe/index.js

Story: https://app.asana.com/0/1191220738645130/1200227593157533

cart issues 2 (Doordash)

---

src/components/Footer/index.js
src/themes/two/src/components/Footer/index.js
template/app.js

Footer page

---

src/themes/two/src/components/AddressForm/index.js
src/themes/two/src/components/AddressForm/styles.js
src/themes/two/src/components/AddressList/index.js
src/utils/index.js

Story: https://app.asana.com/0/1191220738645130/1200262965073974, https://app.asana.com/0/1191220738645130/1200267252742505
Demos: https://d.pr/v/UVTdKw, https://d.pr/v/FRA40V

[FIX] address list adjust pin and bug

---

src/themes/two/src/components/UserDetails/index.js
src/themes/two/src/components/UserFormDetails/index.js

[ADD] userDetails for checkout (Doordash)

---

src/themes/two/src/components/ForgotPasswordForm/index.js
src/themes/two/src/components/ForgotPasswordForm/styles.js

Story: https://app.asana.com/0/1191220738645130/1200263156969997
Demo: https://d.pr/v/GWCDCT

[FIX] forgot password (Doordash)

---

src/themes/two/src/components/BusinessProductsListing/index.js
src/themes/two/src/components/Cart/index.js
src/themes/two/src/components/Modal/index.js
src/themes/two/src/components/Modal/styles.js
src/themes/two/src/components/UpsellingPage/index.js

demo: https://d.pr/v/C2Wpzj
Story: https://app.asana.com/0/1191220738645130/1200267252742507

[FIX] product comment view (Doordash)

---

src/themes/two/src/components/FilterBusinessesListing/index.js
src/themes/two/src/styles/Buttons/index.js

https://app.asana.com/0/1200310580837786/1200303763373858/f

Nav issues

---

src/components/OrdersOption/index.js

Merge first https://github.com/Ordering-Inc/ordering-components/pull/383

Remove orders sort

---

src/components/AddressList/index.js
src/components/Header/index.js
src/components/OrderDetails/index.js
src/components/OrderDetails/styles.js

Call center issues

---

src/components/PaymentOptionCash/index.js

Fix Only numbers for Cash option

Fix Only numbers for Cash option

---

src/components/BusinessBasicInformation/styles.js

Fix, text is now displayed in the box

Fix, text is now displayed in the box

---

src/components/Checkout/styles.js

Before: https://d.pr/v/4RYMxw
After: https://d.pr/v/rUSbqC

This will always fit the text to the yellow box message

---

src/components/PaymentOptionCash/index.js

Extra validation, only allows 0-9

Extra validation, only allows 0-9

---

src/components/VerticalOrdersLayout/styles.js

Improve visual design in my orders

Improve visual design in my orders

---

src/components/BusinessController/index.js
src/components/BusinessController/styles.js

https://app.asana.com/0/1200561475185167/1200456574001489

Time to close business

---

src/components/BusinessController/index.js

[FIX] close timing

---

src/components/SignUpForm/index.js
src/components/SignUpForm/styles.js

The actual functionality of the button hasn't been implemented.

Add button in signup page if business signup allowed

---

src/components/Cart/index.js
src/components/OrderDetails/index.js

[ADD] subtotal with discount for carts

---

src/components/ProductItemAccordion/index.js

[FIX] no ingredients bug on orderDetails

---

src/components/HorizontalOrdersLayout/index.js
src/components/OrdersOption/index.js
src/components/OrdersOption/styles.js

[ADD] preorders block

---

package-lock.json
src/components/Modal/index.js

STORY: https://app.asana.com/0/1198717964402573/1200660212193230

improvement Modal

---

src/components/BusinessesListing/index.js
src/components/BusinessesListing/styles.js
template/pages/BusinessesList/index.js

https://app.asana.com/0/1191220738645130/1200555360910074
Demo: https://d.pr/v/PCP4Qc

[ADD] save pagination for businessList

---

src/components/InputPhoneNumber/index.js
src/components/LoginForm/index.js
src/themes/five/src/components/LoginForm/index.js
src/themes/four/src/components/LoginForm/index.js
src/themes/six/src/components/LoginForm/index.js
src/themes/three/src/components/LoginForm/index.js
src/themes/two/src/components/LoginForm/index.js
src/themes/wow/src/components/LoginForm/index.js
template/theme.json

Now customers can change the text when the page loads.
for :
- LOGIN_WITH_CELLPHONE
- NEW_ON_PLATFORM
- PHONE_NUMBER
See video: https://d.pr/v/2z40IK

Added 2 missing variables.

---

src/components/Messages/index.js

See image: 
Before: https://d.pr/ioprAi
After: https://d.pr/i/igRMiD

Added preparation time and Delivery time variables

---

src/themes/six/src/components/BusinessesListing/index.js
src/themes/six/src/components/LoginForm/index.js
src/themes/six/src/components/LoginForm/styles.js
src/themes/six/src/components/OrderDetails/index.js
src/themes/six/src/components/OrderDetails/styles.js
src/themes/six/src/components/ProductItemAccordion/index.js

react-template-6 (starbucks template) fix point3-  add address map bug fix, change order type bug fix, improve styles most similar design

fix-point3

---

src/themes/five/src/components/LoginForm/index.js

Story: https://app.asana.com/0/1200268243113852/1200714489021229

Fix: login issue

---

src/themes/six/src/components/AddressForm/index.js
src/themes/six/src/components/Cart/index.js
src/themes/six/src/components/CartFullPage/index.js
src/themes/six/src/components/LoginForm/index.js
src/themes/six/src/components/ProductItemAccordion/index.js

At the cart page, after edit product quantity bug fix.

fix-point-4

---

src/themes/six/index.js
src/themes/six/src/components/AppleLogin/index.js
src/themes/six/src/components/AppleLogin/styles.js
src/themes/six/src/components/GoogleLogin/index.js
src/themes/six/src/components/GoogleLogin/styles.js
src/themes/six/src/components/SmsLogin/index.js
src/themes/six/src/components/SmsLogin/styles.js

implements components and style in theme six 
GoogleLoginButton,
AppleLogin,
SmsLoginButton,
Tab

fix:change implements components in theme six

---

src/themes/six/src/components/AppleLogin/styles.js
src/themes/six/src/components/GoogleLogin/styles.js
src/themes/six/src/components/SmsLogin/styles.js

changes importing styles in components in theme six

fix:changes imports in components of styles

---

src/themes/six/src/components/BusinessesListing/index.js
src/themes/six/src/components/CartInfo/index.js
src/themes/six/src/components/OrderDetails/styles.js
src/themes/six/src/components/ProductForm/styles.js

✓  RW Template 6: Issue in store, styles of the description on the store products look wrong 
task directory comment : RW Template 6: Issue in checkout, ASAP button is not unclickable.
✓ RW Template 6: Inside ProductForm, button to add product disappears
✓ RW Template 6: Order Types are not disabled in checkout, allowing you to order with an order type that's not enabled
✓ RW Template 6: Visual Improvement: Order Type Curbside and Drive Thru are switched
✓ RW Template 6: First load of the business doesn't show the business icons

fix point 5 of Template6

---

src/components/Header/index.js

Changed setting validation to string

Changed setting validation to string

---

src/components/OrderTypeSelectorHeader/index.js
src/components/OrderTypeSelectorHeader/styles.js
src/styles/Select/index.js

Improvement Disable Dropdown if only one OrderType

---

src/index.js

fix: adding import of utils verifyDecimals

---

src/components/BusinessProductsListing/index.js
src/themes/eight/src/components/BusinessProductsListing/index.js
src/themes/seven/src/components/BusinessProductsListing/index.js

Fix config add_product_with_one_click
The value comes as a String from api.
false: '0'
true: '1'

Fix config add_product_with_one_click

---

src/components/BusinessItemAccordion/index.js
src/components/BusinessItemAccordion/styles.js

https://app.asana.com/0/1191220738645130/1200983731509899

[add] improve businessItemAccordion style

---

src/styles/Inputs/index.js
src/themes/orderAndPay/src/components/Cart/styles.js
src/themes/orderAndPay/src/components/UpsellingPage/styles.js
src/themes/orderAndPay/src/styles/Inputs/index.js

Finish https://app.asana.com/0/1191220738645130/1200981140797200

Order and pay3

---

src/index.js

description
add components like GoogleLoginButton, SmsLoginButton, AppleLogin

feature: exporting components necesary for custom changes marketplace

---

src/components/PaymentOptionPaypal/index.js

Story: https://app.asana.com/0/1201029220735400/1201025186134368/f

[FIX] Paypal Currency

---

src/components/SignUpForm/index.js
src/components/SignUpForm/styles.js
src/styles/Checkbox/index.js
src/themes/eight/src/components/SignUpForm/index.js
src/themes/eight/src/components/SignUpForm/styles.js
src/themes/five/src/components/SignUpForm/index.js
src/themes/five/src/components/SignUpForm/styles.js
src/themes/four/src/components/SignUpForm/index.js
src/themes/four/src/components/SignUpForm/styles.js
src/themes/franchise/src/components/SignUpForm/index.js
src/themes/franchise/src/components/SignUpForm/styles.js
src/themes/orderAndPay/src/components/SignUpForm/index.js
src/themes/orderAndPay/src/components/SignUpForm/styles.js
src/themes/seven/src/components/SignUpForm/index.js
src/themes/seven/src/components/SignUpForm/styles.js
src/themes/six/src/components/SignUpForm/index.js
src/themes/six/src/components/SignUpForm/styles.js
src/themes/three/src/components/SignUpForm/index.js
src/themes/three/src/components/SignUpForm/styles.js
src/themes/two/src/components/SignUpForm/index.js
src/themes/two/src/components/SignUpForm/styles.js

STORY: https://app.asana.com/0/1198717964402573/1201069818336849

[feat] add the Terms & Conditions

---

src/themes/five/src/components/Header/index.js

Story: https://app.asana.com/0/0/1201079463100837/f

disable-preorder-option Template 5 if config disabled

---

src/themes/four/src/components/Header/index.js

Story: https://app.asana.com/0/0/1201079463100830/f

disable-preorder-option template if config disabled

---

src/themes/three/src/components/Header/index.js

Story: https://app.asana.com/0/0/1201079463100823/f

disable-preorder-option Template 3 if config disable

---

src/themes/two/src/components/Header/index.js

Story: https://app.asana.com/0/0/1201079463100815/f

disable-preorder-optionTemplate2 if config disable.

---

src/themes/four/src/components/Header/index.js
src/themes/three/src/components/Header/index.js
src/themes/two/src/components/Header/index.js

Story: https://app.asana.com/0/1200517202404523/1201050810896955/f

[FIX] Preorder Disable

---

src/components/SignUpForm/index.js
src/themes/eight/src/components/SignUpForm/index.js
src/themes/five/src/components/SignUpForm/index.js
src/themes/four/src/components/SignUpForm/index.js
src/themes/seven/src/components/SignUpForm/index.js
src/themes/six/src/components/SignUpForm/index.js
src/themes/three/src/components/SignUpForm/index.js
src/themes/two/src/components/SignUpForm/index.js

Story: https://app.asana.com/0/1199511033583011/1201140462649636/f
Video: https://d.pr/v/c1dEX3

[FIX] Hide facebook login if disabled in signup page

---

src/components/OrderTypeSelectorHeader/index.js

Story: https://app.asana.com/0/1199511033583011/1201176042099119/f
Video: https://d.pr/v/O0FEcj

[FIX] OrderType Behavior

---

src/components/BusinessesListing/index.js

Story: https://app.asana.com/0/1199511033583011/1201186471360416/f
Video: https://d.pr/v/KE5tlk

[FIX] BusinessListing load skeleton

---

src/themes/five/src/components/BusinessItemAccordion/styles.js
src/themes/five/src/components/BusinessProductsListing/styles.js
src/themes/five/src/components/BusinessReviews/styles.js
src/themes/five/src/components/CartContent/styles.js
src/themes/five/src/components/PaymentOptionCash/index.js
src/themes/five/src/components/SidebarMenu/styles.js
src/themes/franchise/src/components/BusinessItemAccordion/styles.js
src/themes/franchise/src/components/BusinessProductsListing/styles.js
src/themes/franchise/src/components/BusinessReviews/styles.js
src/themes/franchise/src/components/CartContent/styles.js
src/themes/franchise/src/components/PaymentOptionCash/index.js
src/themes/franchise/src/components/SidebarMenu/styles.js
src/themes/pwa/src/components/BusinessItemAccordion/styles.js
src/themes/pwa/src/components/BusinessProductsListing/styles.js
src/themes/pwa/src/components/BusinessReviews/styles.js
src/themes/pwa/src/components/CardForm/styles.js
src/themes/pwa/src/components/CartContent/styles.js
src/themes/pwa/src/components/Modal/styles.js
src/themes/pwa/src/components/MomentContent/styles.js
src/themes/pwa/src/components/OrderTypeSelectorContent/styles.js
src/themes/pwa/src/components/PaymentOptionCash/index.js
src/themes/pwa/src/components/ProductItemAccordion/styles.js
src/themes/pwa/src/components/SidebarMenu/styles.js
src/themes/pwa/src/components/StripeRedirectForm/styles.js

Story: https://app.asana.com/0/1200268243113852/1200555524224843

Pwa feedback

---

src/themes/five/src/components/MomentControl/index.js
src/themes/five/src/components/MomentControl/styles.js
src/themes/franchise/src/components/MomentControl/index.js
src/themes/franchise/src/components/MomentControl/styles.js

Story: https://app.asana.com/0/1200268243113852/1201217478017059

Update: franchise and five calendar

---

src/themes/two/src/components/UserProfileForm/index.js

Story: https://app.asana.com/0/1199550129190624/1201210389339371/f

Language Variable Saved Places

---

src/themes/five/src/components/HighestRated/index.js

Story: https://app.asana.com/0/0/1201286776097992/f
Image: https://d.pr/i/jbS7pf

[FIX] added extra validation

---

src/themes/five/src/components/BusinessProductsCategories/index.js
src/themes/five/src/components/BusinessProductsList/index.js
src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/HighestRated/index.js
src/themes/five/src/components/HighestRated/styles.js
src/themes/franchise/src/components/BusinessProductsCategories/index.js

Story: https://app.asana.com/0/1200268243113852/1201282679145218

[Update] business product scroll and business list page

---

src/themes/eight/src/components/BusinessProductsListing/index.js
src/themes/eight/src/components/BusinessProductsListing/styles.js
src/themes/eight/src/components/Cart/index.js
src/themes/eight/src/components/Cart/styles.js
src/themes/eight/src/components/Checkout/styles.js
src/themes/eight/src/components/Footer/index.js
src/themes/eight/src/components/ProductForm/index.js
src/themes/eight/src/components/ProductForm/styles.js
src/themes/eight/src/components/ProductItemAccordion/styles.js
src/themes/eight/src/components/UserDetails/styles.js

STORY: https://app.asana.com/0/1198717964402573/1201294909272835

[FIX] feedback for template 8

---

src/themes/orderAndPay/src/components/BusinessProductsList/index.js
src/themes/orderAndPay/src/components/BusinessProductsListing/index.js

https://app.asana.com/0/1191220738645130/1201290146690030

[fix] autoscroll categories order and pay

---

src/themes/orderAndPay/src/components/Cart/index.js
src/themes/orderAndPay/src/components/Cart/styles.js
src/themes/orderAndPay/src/components/Checkout/index.js
src/themes/orderAndPay/src/components/Checkout/styles.js
src/themes/orderAndPay/src/components/FloatingButton/index.js
src/themes/orderAndPay/src/components/FloatingButton/styles.js
src/themes/orderAndPay/src/components/ProductForm/index.js
src/themes/orderAndPay/src/components/ProductForm/styles.js

https://app.asana.com/0/1191220738645130/list

productform padding when OS is iphone

---

src/themes/five/src/components/Checkout/index.js
src/themes/five/src/components/LoginForm/styles.js
src/themes/five/src/components/ProductItemAccordion/styles.js
src/themes/five/src/components/SignUpForm/styles.js
src/themes/franchise/src/components/Checkout/index.js
template/pages/Checkout/index.js

Story: https://app.asana.com/0/1200268243113852/1201340018538452

[Update]: template-5

---

src/components/LoginForm/index.js

Story: https://app.asana.com/0/1199511033583011/1201333851191078/f
Video: https://d.pr/v/t8jsKP

[FIX] empty when tab not selected

---

src/themes/five/src/components/BusinessesListing/styles.js
src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/ProductForm/styles.js
src/themes/five/src/components/RenderProductsLayout/index.js
src/themes/five/src/components/RenderProductsLayout/styles.js

Story: https://app.asana.com/0/1200268243113852/1201355239172411

Original feedback

---

src/components/GoogleIdentity/index.js
src/components/LoginForm/index.js

https://app.asana.com/0/1191220738645130/1199519667039476

google login identity

---

src/themes/five/src/components/BusinessItemAccordion/styles.js
src/themes/five/src/components/Cart/styles.js
src/themes/franchise/src/components/ProductForm/styles.js

Story: https://app.asana.com/0/1200268243113852/1201363149240020
https://app.asana.com/0/1200268243113852/1201341826641745

[Update]: template-5 and franchise

---

src/themes/three/src/components/HomeHero/styles.js

Story: https://app.asana.com/0/0/1201402310022429/f

Add title color change

---

src/themes/franchise/src/components/MySavedPlaces/index.js

Story: https://app.asana.com/0/1200268243113852/1201341826641752

Update: MySavedPlaces on franchise

---

src/themes/franchise/src/components/BusinessController/index.js
src/themes/franchise/src/components/BusinessController/styles.js
src/themes/franchise/src/components/BusinessesMap/index.js
template/pages/BusinessesList/index.js

Story: https://app.asana.com/0/1200268243113852/1201382613814477

Franchise update

---

src/components/OrderSuccessModal/index.js

Story: https://app.asana.com/0/1199511033583011/1201439765372927/f

[FIX] validate if value null

---

src/themes/seven/src/components/Cart/index.js

Story: https://app.asana.com/0/0/1201449571425029/f

FIX coupons

---

src/components/PaymentOptions/index.js

Story: https://app.asana.com/0/1199511033583011/1201447254620465/f

[FIX] extra validation

---

src/themes/four/src/components/Checkout/index.js
src/themes/three/src/components/Checkout/index.js
src/themes/two/src/components/Checkout/index.js

Story: https://app.asana.com/0/1199511033583011/1201475623240468/f
Video: https://d.pr/v/WMLXll

[FIX] Payment method state

---

package-lock.json
src/themes/franchise/src/components/BusinessesListing/index.js
src/themes/franchise/src/components/BusinessesMap/index.js

Story: https://app.asana.com/0/1200268243113852/1201483892059708

[Update]: Business search on franchise template

---

src/components/LastOrders/index.js
src/components/LastOrders/styles.js
src/themes/eight/index.js
src/themes/eight/src/components/BusinessProductsListing/index.js
src/themes/eight/src/components/BusinessesListing/index.js
src/themes/eight/src/components/BusinessesListing/styles.js
src/themes/eight/src/components/Checkout/styles.js
src/themes/eight/src/components/Footer/index.js
src/themes/eight/src/components/Footer/styles.js
src/themes/eight/src/components/OrderDetails/index.js
src/themes/eight/src/components/OrderDetails/styles.js
src/themes/eight/src/components/SingleProductCard/index.js
src/themes/eight/src/components/SingleProductCard/styles.js
src/themes/eight/src/components/UserProfileForm/ProfileOptions/index.js
src/themes/eight/src/components/UserProfileForm/ProfileOptions/styles.js
src/themes/eight/src/components/UserProfileForm/index.js
src/themes/eight/src/components/UserProfileForm/styles.js
src/themes/eight/src/styles/Selects/index.js

STORY: https://app.asana.com/0/1198717964402573/1201483892059712

[Fix] feedback

---

src/components/OrderDetails/index.js

Demo: https://d.pr/v/1Gbc3u
show the placing order modal when the page comes to order details page from only checkout page

[Fix] placing order modal

---

package-lock.json
src/themes/pwa/src/components/ProductForm/index.js

Story: https://app.asana.com/0/1200268243113852/1201499161841373

Update: Pwa product form

---

src/components/ProductForm/index.js
src/themes/five/src/components/Modal/styles.js
src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/ProductForm/styles.js
src/themes/four/src/components/ProductForm/index.js
src/themes/four/src/components/ProductForm/styles.js
src/themes/franchise/src/components/ProductForm/index.js
src/themes/franchise/src/components/ProductForm/styles.js
src/themes/pwa/src/components/ProductForm/index.js
src/themes/pwa/src/components/ProductForm/styles.js
src/themes/three/src/components/ProductForm/index.js
src/themes/three/src/components/ProductForm/styles.js
src/themes/two/src/components/ProductForm/index.js
src/themes/two/src/components/ProductForm/styles.js
template/pages/BusinessProductsList/index.js

Story: https://app.asana.com/0/1200268243113852/1201521788945732

[Feat]: Multiple photos to all templates

---

src/components/ProductForm/index.js
src/themes/five/src/components/ProductForm/index.js
src/themes/four/src/components/ProductForm/index.js
src/themes/franchise/src/components/BusinessProductsListing/styles.js
src/themes/franchise/src/components/ProductForm/index.js
src/themes/franchise/src/components/ProductItemAccordion/index.js
src/themes/pwa/src/components/ProductForm/index.js
src/themes/three/src/components/ProductForm/index.js
src/themes/two/src/components/ProductForm/index.js

Story: https://app.asana.com/0/1200268243113852/1201546316810603

[Update]: franchise mobile feedback

---

src/themes/franchise/src/components/BusinessesListing/index.js

Story: https://app.asana.com/0/1200268243113852/1201532548230196

Franchise business

---

src/components/ProductForm/styles.js
src/themes/five/src/components/ProductForm/styles.js
src/themes/four/src/components/ProductForm/styles.js
src/themes/franchise/src/components/ProductForm/styles.js
src/themes/pwa/src/components/ProductForm/index.js
src/themes/pwa/src/components/ProductForm/styles.js
src/themes/three/src/components/ProductForm/styles.js
src/themes/two/src/components/ProductForm/styles.js
template/pages/BusinessProductsList/index.js

Story: https://app.asana.com/0/1200268243113852/1201522322436212

Multiple photos feedback

---

src/components/Cart/index.js

Story: https://app.asana.com/0/1199511033583011/1201547785113178/f
Video: https://d.pr/v/MBBwdD

[FIX] hide service fee if 0

---

src/components/ProductForm/index.js
src/themes/eight/src/components/ProductForm/index.js
src/themes/five/src/components/ProductForm/index.js
src/themes/four/src/components/ProductForm/index.js
src/themes/franchise/src/components/ProductForm/index.js
src/themes/orderAndPay/src/components/ProductForm/index.js
src/themes/pwa/src/components/ProductForm/index.js
src/themes/seven/src/components/ProductForm/index.js
src/themes/six/src/components/ProductForm/index.js
src/themes/three/src/components/ProductForm/index.js
src/themes/two/src/components/ProductForm/index.js
src/themes/wow/src/components/ProductForm/index.js

Story: https://app.asana.com/0/1199511033583011/1201541719706859/f

[FIX] show only suboptions enabled

---

src/components/ProductForm/index.js
src/components/ProductForm/styles.js

Story: https://app.asana.com/0/1200550251832819/1201489117570766
Demo: https://d.pr/v/7l3Wj4

Add estimated amount

---

src/components/ProductForm/styles.js
src/themes/four/src/components/ProductForm/styles.js
src/themes/three/src/components/ProductForm/styles.js
src/themes/two/src/components/ProductForm/styles.js
template/pages/BusinessProductsList/index.js

Story: https://app.asana.com/0/1200268243113852/1201590683570203

Image overlap

---

src/components/UserProfileForm/index.js

Story: https://app.asana.com/0/1199511033583011/1201547699466898/f

[FIX] rtl phone number

---

src/components/UpsellingPage/index.js

Story: https://app.asana.com/0/1199511033583011/1201609083368174/f
Video: https://d.pr/v/HqnUMg

[FIX] Upselling not taking to checkout

---

src/components/UpsellingPage/index.js

Story: https://app.asana.com/0/0/1201611291285561/f
Video: https://d.pr/v/zrqetk

[FIX] upselling missing change

---

src/themes/four/src/components/UserProfileForm/index.js
src/themes/two/src/components/UserProfileForm/index.js

Story: https://app.asana.com/0/0/1201613745205659/f

[FIX] Phone RTL Template 2, 4

---

src/components/BusinessReviews/index.js
src/themes/orderAndPay/src/components/BusinessReviews/index.js
src/themes/six/src/components/BusinessReviews/index.js

Story: https://app.asana.com/0/1199511033583011/1201615393949549/f

[FIX] add language variable all in business reviews

---

src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/ProductForm/styles.js
src/themes/four/src/components/ProductForm/index.js
src/themes/four/src/components/ProductForm/styles.js
src/themes/franchise/src/components/ProductForm/index.js
src/themes/franchise/src/components/ProductForm/styles.js
src/themes/orderAndPay/src/components/ProductForm/index.js
src/themes/orderAndPay/src/components/ProductForm/styles.js
src/themes/three/src/components/ProductForm/index.js
src/themes/three/src/components/ProductForm/styles.js
src/themes/two/src/components/ProductForm/index.js
src/themes/two/src/components/ProductForm/styles.js

Story: https://app.asana.com/0/1200550251832819/1201489117570766/1201619700674461/f

apply estimated person in web templates

---

src/utils/index.js

Story: https://app.asana.com/0/0/1201631352269175/f

[FIX] Add language variables

---

src/components/SmartAppBanner/index.js

Story: https://app.asana.com/0/1199511033583011/1201722670330261/f

[FIX] Dynamic text

---

index.js
src/index.js

Story: https://app.asana.com/0/0/1201758265387001/f

[FIX] Missing imports

---

src/components/BusinessProductsList/index.js

Story: https://app.asana.com/0/home/1200550251832815/1201187513910289
Demo: https://d.pr/v/4qa4pU

sort product according to rank

---

src/themes/five/src/components/BusinessPreorder/index.js

Story: https://app.asana.com/0/1200268243113852/1201758652216787

Update: preorder style

---

src/components/SingleProductCard/styles.js
src/themes/two/src/components/SingleProductCard/styles.js

Story: https://d.pr/v/ZV9nah
Demo: https://d.pr/v/Orh7tx

fix bug product name align when RTl

---

src/components/ProductForm/index.js
src/components/ProductForm/styles.js
src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/ProductForm/styles.js

Demo:
https://d.pr/v/QH6UPP
https://d.pr/i/1gCMx8

show calories in product form

---

src/components/ProductForm/styles.js
src/themes/five/src/components/ProductForm/styles.js

bug depending on the product name size

calories feedback

---

src/themes/three/src/components/LoginForm/index.js

Story: https://app.asana.com/0/0/1201868626592700/f

[ADD] default language

---

src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/ProductForm/styles.js

Story: https://app.asana.com/0/1200550251832819/1201694040067881/f
Demo: https://d.pr/v/tGRyTz

add product weight in Origin Template

---

src/components/Header/index.js
src/components/HeaderOption/index.js
src/components/MomentContent/index.js
src/components/MomentControl/index.js
src/components/MomentControl/styles.js

Story: https://app.asana.com/0/1199511033583011/1201787189512842/f
Video: https://d.pr/v/CUV6mj

[FIX] update moment

---

src/themes/five/src/components/Footer/styles.js
src/themes/five/src/components/Header/index.js
template/app.js

Story: https://app.asana.com/0/1200268243113852/1201913937946346

Update: language selector on Header

---

src/themes/two/src/components/Header/index.js
src/themes/two/src/components/HeaderOption/index.js
src/themes/two/src/components/MomentContent/index.js
src/themes/two/src/components/MomentControl/index.js
src/themes/two/src/components/MomentControl/styles.js

Story: https://app.asana.com/0/1201859974879441/1201929853624104/f

[FIX] moment asap for template 2

---

src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/ProductForm/styles.js

improve style to more similar as design

---

src/themes/five/src/components/Footer/styles.js
src/themes/five/src/components/Header/index.js

Story: https://app.asana.com/0/1200268243113852/1201932246378112

Update: footer

---

src/themes/five/src/components/ProductForm/styles.js
src/themes/five/src/components/SingleProductCard/index.js
yarn.lock

STORY: 
https://app.asana.com/0/1198717964402573/1201896974690167
https://app.asana.com/0/1198717964402573/1201930253258910

[Fix] hide for price 0 and pre line

---

src/components/Header/index.js
src/themes/callcenterOriginal/src/components/Header/index.js
src/themes/five/src/components/Header/index.js
src/themes/five/src/components/ProductOptionSubOption/index.js
src/themes/four/src/components/Header/index.js
src/themes/franchise/src/components/Header/index.js
src/themes/three/src/components/Header/index.js
src/themes/two/src/components/Header/index.js

Story: https://app.asana.com/0/1200268243113852/1201974520684105

Update: product suboption

---

src/themes/five/src/components/PaymentOptions/index.js

Story: https://app.asana.com/0/1199511033583011/1201936820213163/f
Video: https://d.pr/v/cEJqYF

[FIX] when reload payment method paypal

---

src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/ProductForm/styles.js

add youtube video gallery in original template

---

src/themes/three/src/components/BusinessesListing/styles.js

Story: https://app.asana.com/0/0/1202012962661861/f

ADD color theme styles

---

src/themes/five/src/components/ProductOptionSubOption/index.js
template/pages/BusinessProductsList/index.js
yarn.lock

Story: https://app.asana.com/0/1200268243113852/1202012981603347

[Update]: Product subOption select

---

src/themes/five/src/components/BusinessPreorder/index.js

Story: https://app.asana.com/0/1200268243113852/1201971621479549

Update: BusinessPreorder

---

src/themes/five/src/components/ProductForm/index.js

STORY: https://app.asana.com/0/1198717964402573/1202057642513685

[Fix] max quantity setting issue

---

src/themes/five/src/components/Footer/index.js

Story: https://app.asana.com/0/0/1202076661949990/f
Video: https://d.pr/v/S8msbu

[FIX] allow footer as cms

---

src/themes/five/src/components/ProductForm/index.js

Story: https://app.asana.com/0/1200550251832819/1202075802560497
Demo: https://d.pr/v/cl1DGO

allow play all Youtube url

---

src/themes/three/src/components/AddressList/index.js
template/pages/BusinessProductsList/index.js

Story: https://app.asana.com/0/1199511033583011/1202072619753802/f

[FIX] misspelled language variable, missing param

---

src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/ProductOptionSubOption/index.js

Template Five Demo:  https://d.pr/v/cMdSdV

auto scrolling next option in product form

---

src/components/MomentControl/index.js
src/themes/five/src/components/MomentControl/index.js

Story: https://app.asana.com/0/1202080309393054/1201929203943938/f
Video: https://d.pr/v/7FhRjP

[FIX] validate config

---

src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/ProductForm/styles.js

Story: https://app.asana.com/0/home/1200550251832815/1201126531558193
Demo: https://d.pr/v/X7I4qn

quantity limit according to minimum and maximum

---

src/themes/callcenterOriginal/src/components/OrderDetails/index.js
src/themes/callcenterOriginal/src/components/OrderDetails/styles.js

add button to new order to

---

src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/ProductForm/styles.js

STORY: https://app.asana.com/0/home/1200550251832815/1202175772465612
DEMO:  https://d.pr/v/U1fCFS

bug to add product cart when maximum quantity is null

---

src/themes/callcenterOriginal/src/components/OrderDetails/index.js

Story: https://app.asana.com/0/1200550251832819/1202183330391825
Demo:  https://d.pr/v/bSvfwd

change redirect to Home

---

src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/ProductForm/styles.js
src/themes/five/src/components/ProductOptionSubOption/index.js
template/pages/BusinessProductsList/index.js

Story : https://app.asana.com/0/home/1200550251832815/1202175897616918
Demo :  https://d.pr/v/QVkVYg

Feedback auto scroll next option

---

src/themes/five/src/components/BusinessProductsCategories/styles.js
src/themes/five/src/components/RenderProductsLayout/styles.js

Story: https://app.asana.com/0/1199511033583011/1202175310865611/f
Video: https://d.pr/v/eXZmR5

[FIX] styles business categories

---

src/themes/five/src/components/BusinessController/index.js
src/themes/five/src/components/BusinessPreorder/index.js
src/themes/five/src/components/BusinessesListing/index.js

Storys: 
https://app.asana.com/0/0/1202206739182450/f
https://app.asana.com/0/0/1202206739182451/f
Videos: 
https://d.pr/v/IB6eeu
https://d.pr/v/I9T55r

[FEAT] update business information

---

src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/ProductForm/styles.js

Story: https://app.asana.com/0/0/1202206739182452/f
Video: https://d.pr/i/pj80xl

[FEAT] change design

---

src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/OrderDetails/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202224356221559
Demo: https://d.pr/v/4nNqVf

remove item from cart

---

src/themes/five/src/components/BusinessBasicInformation/index.js
src/themes/five/src/components/BusinessPreorder/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202253505195835
Demo: https://d.pr/v/7sOhZ1, https://d.pr/v/KTJ9bJ

hide calendar when preorder is disable

---

src/themes/five/src/components/Footer/index.js

Story: https://app.asana.com/0/0/1202175310865614/f
Video: https://d.pr/v/1YUZEK

[FEAT] prevent overflow

---

src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/BusinessProductsListing/styles.js

Story: https://app.asana.com/0/0/1202206637477697/f
Video: https://d.pr/v/lJ3IAf

[FEAT] change button design

---

package.json
src/themes/five/src/components/LinkableText/index.js
src/themes/five/src/components/ProductForm/index.js
yarn.lock

Story: https://app.asana.com/0/1199511033583011/1202211714291087/f
Video: https://d.pr/v/pRNK40

[FEAT] linkify product description

---

src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/RenderProductsLayout/index.js

Story: https://app.asana.com/0/0/1202267962701769/f
Video: https://d.pr/v/n6b1BD

[FEAT] Hide cart button when empty

---

src/themes/five/src/components/BusinessController/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202226033684628
Demo: https://d.pr/v/r1u3FR

fix hide-preorder issue

---

src/themes/five/src/components/Checkout/index.js
src/themes/five/src/components/PaymentOptionWallet/index.js

STORY: https://app.asana.com/0/1198717964402573/1202271877726673

[Add] validate wallets for business configs

---

src/themes/five/src/components/BusinessController/index.js

Story: https://app.asana.com/0/1202177152901831/1202292581683707/f
Image: https://d.pr/i/CKWEd2

[FIX] validation

---

src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/OrderDetails/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202224356221558
Demo: https://d.pr/v/Txyjk2

Feedback reorder

---

src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/OrderDetails/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202224356221558
Demo: https://d.pr/v/AKAJi4

Feedback reorder 1

---

src/themes/three/src/components/MomentControl/index.js
src/themes/three/src/styles/Select/index.js

Story: https://app.asana.com/0/1199511033583011/1202287948076942/f
Video: https://d.pr/v/aCQrlu

[FEAT] Fix scroll bar

---

src/themes/four/index.js

Story: https://app.asana.com/0/0/1202352983490962/f

[FEAT] Missing exports

---

src/themes/five/index.js

[ADD] missing import

---

src/themes/five/src/components/LoginForm/styles.js

https://app.asana.com/0/1199511033583011/1202326424586299/f
Video: https://d.pr/v/zHG1sL

[FEAT] Image style

---

src/themes/five/src/components/Wallets/index.js

Story: https://app.asana.com/0/1202390334219072/1202383139432347/f

[FEAT] fix validation

---

src/themes/five/src/components/SessionsList/index.js
src/themes/five/src/components/SessionsList/styles.js
src/themes/five/src/components/SidebarMenu/index.js

STORY: https://app.asana.com/0/inbox/1198717964396322/1202378112606652/1202391640990764

[Fix] Sessions feedback

---

src/themes/five/src/components/BusinessBasicInformation/index.js
src/themes/five/src/components/Checkout/index.js
src/themes/five/src/components/DriverTips/index.js

STORY: https://app.asana.com/0/1198717964402573/1202408352443025

[Fix] driver tip

---

src/themes/five/src/components/BusinessItemAccordion/index.js
src/themes/five/src/components/BusinessItemAccordion/styles.js
src/themes/five/src/components/Cart/index.js
src/themes/five/src/components/Checkout/index.js

STORY: https://app.asana.com/0/inbox/1198717964396322

[Add] allow the store to change

---

src/themes/four/src/components/HomeHero/styles.js

Story: https://app.asana.com/0/1199511033583011/1202420647453400/f
Video: https://d.pr/i/NpGPvv

[FEAT] change for template 4

---

src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/OrderDetails/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202224356221559
Demo: https://d.pr/v/NSzSR6

fix reorder issue

---

src/themes/two/src/components/LoginForm/index.js
src/themes/two/src/components/LoginForm/styles.js
src/themes/two/src/components/SignUpForm/index.js
src/themes/two/src/components/SignUpForm/styles.js

Story: https://app.asana.com/0/1199511033583011/1202458534194187/f
Video: https://d.pr/v/K0jiHu

[FEAT] Add reCaptcha for Template 2

---

src/themes/five/src/components/BusinessListingSearch/index.js
src/themes/five/src/components/BusinessListingSearch/styles.js
src/themes/five/src/styles/Buttons/index.js

Story: https://app.asana.com/0/1200268243113852/1202408286159614

[Feat]: price filter

---

src/themes/five/src/components/HorizontalOrdersLayout/index.js
src/themes/five/src/components/OrdersOption/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202118574026501
Demo: https://d.pr/v/Jl4Av2

add new reorder function

---

src/themes/five/src/components/RenderProductsLayout/index.js

Demo: https://d.pr/v/TB0iwV
STORY: https://app.asana.com/0/1198717964402573/1202506869698927

[Fix] blink issue

---

src/themes/five/src/components/MomentControl/Layouts/CustomLayout/index.js
src/themes/five/src/components/MomentControl/Layouts/CustomLayout/styles.js
src/themes/five/src/components/MomentControl/index.js

STORY: https://app.asana.com/0/1198717964402573/1202511439274443
DEMO: https://d.pr/i/S3Jx5y?showPanel=1

[Add] new custom layout for Moment

---

src/components/DriverTips/index.js
src/themes/five/src/components/DriverTips/index.js
src/themes/four/src/components/DriverTips/index.js
src/themes/three/src/components/DriverTips/index.js
src/themes/two/src/components/DriverTips/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202495350549661
Demo: https://d.pr/v/Kd3a2s

Feedback driver tip

---

src/components/ProductForm/styles.js
src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/four/src/components/ProductForm/styles.js
src/themes/three/src/components/ProductForm/styles.js
src/themes/two/src/components/ProductForm/styles.js

Story: https://app.asana.com/0/1200268243113852/1202518327539580

Update: description display

---

src/themes/five/src/components/DriverTips/index.js

Story: https://app.asana.com/0/1200550251832819/1202548061400069
Demo: https://d.pr/v/EJkEc8

only show one tip option

---

src/themes/five/src/components/MultiCheckout/index.js
src/themes/five/src/components/MultiCheckout/styles.js

STORY: https://app.asana.com/0/inbox/1198717964396322/1202625099398697/1202544086266330

[Add] maximum carts validation

---

src/themes/five/src/components/BusinessListingSearch/index.js
src/themes/five/src/components/OrdersOption/PreviousBusinessOrdered/index.js
src/themes/five/src/components/OrdersOption/PreviousProductsOrdered/index.js
src/themes/five/src/components/OrdersOption/index.js
src/themes/five/src/components/SidebarMenu/index.js
src/themes/five/src/components/SingleOrderCard/index.js
src/themes/five/src/components/SingleProductCard/index.js
src/themes/five/src/components/UserPopover/index.js

Story: https://app.asana.com/0/1200268243113852/1202467325262254

[Update]: Favorite update

---

src/themes/five/src/components/MultiCartsPaymethodsAndWallets/index.js
src/themes/five/src/components/MultiCartsPaymethodsAndWallets/styles.js
src/themes/five/src/components/MultiOrdersDetails/styles.js

STORY: https://app.asana.com/0/1198717964402573/1202638510840804

[Fix] Multi checkout feedback

---

src/themes/five/src/components/BusinessItemAccordion/index.js

STORY: https://app.asana.com/0/1198717964402573/1202647059938491

[Add] business changeable validation

---

src/themes/five/src/components/BusinessProductsList/index.js
src/themes/five/src/components/ServiceForm/index.js

Story: https://app.asana.com/0/1200268243113852/1202473893483630

[Update]: booking functionality

---

src/themes/five/src/components/Checkout/index.js
src/themes/five/src/components/UserDetails/index.js
src/themes/five/src/components/UserFormDetails/index.js

Story: https://app.asana.com/0/1200268243113852/1202675818264449

[Update]: Improvement checkout

---

src/themes/five/src/components/LoginForm/index.js
src/themes/five/src/components/LoginForm/styles.js
src/themes/five/src/components/SignUpForm/index.js
template/app.js

Story: https://app.asana.com/0/home/1200550251832815/1202677874577115
Demo: https://d.pr/v/Kq3wwL, https://d.pr/v/01iakX

Setting login email phone

---

src/themes/three/src/components/BusinessController/index.js
src/themes/three/src/components/Header/index.js

STORY: https://app.asana.com/0/1198717964402573/1202661100351228

[Update] Style for template 3

---

src/themes/five/index.js

Story: https://app.asana.com/0/1201324366625225/1202696204189726/f

[FEAT] Missing export component PlaceSpot

---

src/themes/five/src/components/BusinessBasicInformation/index.js
src/themes/five/src/components/BusinessBasicInformation/styles.js

Story: https://app.asana.com/0/1200268243113852/1202678272167132

[Feat]: social icons

---

src/themes/five/src/components/FavoriteList/index.js
src/themes/five/src/components/SingleProductCard/index.js

Story: https://app.asana.com/0/inbox/1200268243109536

Update: favorite list

---

src/themes/five/src/components/Messages/index.js

Story: https://app.asana.com/0/1199511033583011/1202541961761827/f
Image: https://d.pr/i/h2VHav

[FEAT] logistic tags

---

src/themes/five/src/components/MomentControl/index.js

Story: https://app.asana.com/0/1199511033583011/1202575006551267/f
Image: https://d.pr/i/Vm7ign

[FEAT] set locale moment variables

---

src/themes/five/src/components/BusinessBasicInformation/index.js
src/themes/five/src/components/BusinessBasicInformation/styles.js

Story: https://app.asana.com/0/1200268243113852/1202714062882767

Update: social network

---

src/themes/five/src/components/SignUpForm/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202721157746581
Demo: https://d.pr/v/TwnZ0F

Feedback improve signup

---

src/themes/five/src/components/MyOrders/index.js

Story: https://app.asana.com/0/1199511033583011/1202691588898152/f

[FEAT] Fix language variable

---

src/themes/five/index.js
src/themes/five/src/components/OrderDetails/index.js
src/themes/five/src/components/ReviewDriver/index.js
src/themes/five/src/components/ReviewDriver/styles.js
src/themes/five/src/components/ReviewOrder/index.js
src/themes/five/src/components/ReviewOrder/styles.js
src/themes/five/src/components/ReviewProduct/index.js
src/themes/five/src/components/ReviewProduct/styles.js
src/themes/five/src/components/SingleOrderCard/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202218735742289
Demo: https://d.pr/v/XlwEPp

New review flow

---

src/themes/four/src/components/AccordionDropdown/index.js
src/themes/four/src/components/AccordionDropdown/styles.js
src/themes/four/src/components/BusinessProductsCategories/index.js
src/themes/four/src/components/BusinessProductsCategories/layouts/groceries/index.js
src/themes/four/src/components/BusinessProductsCategories/layouts/groceries/styles.js
src/themes/four/src/components/BusinessProductsList/layouts/groceries/index.js
src/themes/four/src/components/BusinessProductsList/layouts/groceries/styles.js
src/themes/four/src/components/BusinessProductsListing/index.js
src/themes/four/src/components/BusinessProductsListing/styles.js
src/themes/four/src/components/NotFoundSource/index.js
src/themes/four/src/components/NotFoundSource/styles.js
src/themes/four/src/components/RenderProductsLayout/index.js
src/themes/four/src/components/RenderProductsLayout/styles.js

STORY: https://app.asana.com/0/1198717964402573/1202565334049748

[Fix] feedback for template 4

---

src/themes/five/src/components/BusinessPreorder/index.js
src/themes/five/src/components/BusinessPreorder/styles.js
src/themes/five/src/components/BusinessesListing/layouts/AppointmentsBusinessListing/index.js
src/themes/five/src/components/BusinessesListing/layouts/AppointmentsBusinessListing/styles.js
src/themes/five/src/components/RenderProductsLayout/index.js
src/themes/five/src/components/RenderProductsLayout/styles.js
src/themes/five/src/components/ServiceForm/index.js
src/themes/five/src/components/ServiceForm/styles.js

Story: https://app.asana.com/0/1200268243113852/1202721157746550

Update: booking

---

src/themes/five/src/components/OrderDetails/OrderHistory.js
src/themes/five/src/components/OrderDetails/index.js
src/themes/five/src/components/OrderDetails/styles.js
template/pages/OrderDetails/index.js

Story: https://app.asana.com/0/1200268243113852/1202677854889996

Feat: order history

---

src/themes/five/src/components/UserPopover/index.js

Story: https://app.asana.com/0/1200268243113852/1202677901397930

[Update]: Search page

---

src/themes/five/src/components/FavoriteList/index.js
src/themes/five/src/components/FavoriteList/styles.js

Story: https://app.asana.com/0/1200268243113852/1202779736874943

Update: favorite

---

src/themes/five/src/components/SignUpForm/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202778798838779
Demo: https://d.pr/v/Q5VsY8

feedback signup settings

---

src/themes/five/src/components/OrderDetails/index.js
src/themes/five/src/components/ReviewOrder/index.js
src/themes/five/src/components/SingleOrderCard/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202777500306880

feedback new review flow

---

src/themes/five/src/components/UserFormDetails/index.js

Story: https://app.asana.com/0/1200268243113852/1202779921998301

[Update]: phone verify

---

src/themes/five/src/components/SignUpForm/index.js

STORY: https://app.asana.com/0/1198717964402573/1202790369874202

[Update] Facebook login check

---

src/themes/five/src/components/BusinessPreorder/index.js
src/themes/five/src/components/ProfessionalProfile/styles.js
src/themes/five/src/components/ServiceForm/index.js
src/themes/five/src/components/ServiceForm/styles.js

Story: https://app.asana.com/0/1200268243113852/1202792914999578

Update: booking functionality

---

src/themes/five/src/components/Checkout/index.js
src/themes/five/src/components/UserDetails/index.js

Story: https://app.asana.com/0/1200268243113852/1202792389154637

Update: checkout

---

src/themes/five/src/components/ReviewTrigger/index.js
src/themes/five/src/components/ReviewTrigger/styles.js

Story: https://app.asana.com/0/home/1200550251832815/1202808927091149
Demo: https://d.pr/v/K9qauB

improvement new review flow

---

src/components/LastOrders/index.js
src/themes/five/src/components/LastOrders/index.js
src/themes/four/src/components/LastOrders/index.js
src/themes/three/src/components/LastOrders/index.js
src/themes/two/src/components/LastOrders/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202799394390994
Demo: https://d.pr/v/gfMohp

feedback wrong format

---

src/themes/five/src/components/BusinessController/index.js
src/themes/five/src/components/CartContent/index.js
src/themes/five/src/components/OrderDetails/index.js
src/themes/five/src/components/OrderDetails/styles.js
src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/ProductForm/styles.js
src/themes/five/src/components/ProductOption/styles.js
src/themes/five/src/components/SearchProducts/index.js
src/themes/five/src/components/SingleOrderCard/index.js
src/themes/five/src/components/SingleProductCard/index.js

Story: https://app.asana.com/0/1200268243113852/1202787208769552

[Update]: Customer feedback

---

src/themes/four/src/components/BusinessBasicInformation/index.js
src/themes/four/src/components/BusinessProductsCategories/layouts/groceries/index.js
src/themes/four/src/components/BusinessProductsList/layouts/groceries/index.js
src/themes/four/src/components/SingleProductCard/index.js

STORY: https://app.asana.com/0/1198717964402573/1202784076056311

[Fix] template 4 feedback

---

src/themes/five/src/components/ProductForm/index.js

STORY: https://app.asana.com/0/1198717964402573/1202465957411018

[Add] unaddressed orders validations

---

src/themes/five/src/components/BusinessListingSearch/index.js

Story: https://app.asana.com/0/1200268243113852/1202816042188286

Update: hidden previous order

---

src/themes/five/src/components/BusinessProductsCategories/index.js
src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/RenderProductsLayout/styles.js

Story: https://app.asana.com/0/home/1200550251832815/1202832127821125
Demo: https://d.pr/v/tdCLh5

feedback responsive floating

---

src/themes/five/src/components/Modal/styles.js
src/themes/five/src/components/MomentControl/index.js
src/themes/five/src/components/MomentControl/styles.js
src/themes/five/src/components/OrderDetails/index.js
src/themes/five/src/components/OrderDetails/styles.js

Story: https://app.asana.com/0/1200550251832819/1202840187204723
1 subtask demo: https://d.pr/v/Qw6LBF
2 subtask demo: https://d.pr/i/uCEUfS
3 subtask demo: https://d.pr/i/4xDKiL
4 subtask demo: https://d.pr/v/gvXtpY
5 subtask demo: https://d.pr/v/HOQuK0

Feedback improvements pwa

---

src/themes/five/src/components/BusinessProductsCategories/index.js
src/themes/five/src/components/BusinessProductsCategories/styles.js
src/themes/five/src/components/Cart/styles.js
src/themes/five/src/components/RenderProductsLayout/styles.js

Story: https://app.asana.com/0/home/1200550251832815/1202848000355487
1 subtask demo: https://d.pr/v/D8lY07
2 subtask demo: https://d.pr/v/wf6YAw

update responsive style

---

src/themes/five/src/components/OrderDetails/index.js
src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/ProductOption/index.js

Story: https://app.asana.com/0/1200268243113852/1202787208769552

[Update]: Feedback

---

src/themes/five/src/components/ProductForm/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202852021445600
Demo:  https://d.pr/v/MML72x

auto min order quantity

---

src/themes/five/src/components/BusinessInformation/styles.js

Story: https://app.asana.com/0/1200550251832819/1202862496751483
Demo: https://d.pr/v/JZZbDr

update business info page

---

src/themes/five/src/components/BusinessProductsCategories/index.js
src/themes/five/src/components/RenderProductsLayout/index.js
src/themes/five/src/components/SingleProductCard/styles.js

Story: https://app.asana.com/0/1200550251832819/1202850483321116
Demo: https://d.pr/v/hhRStB

resolve image overlap

---

src/themes/five/src/components/BusinessProductsCategories/index.js
src/themes/five/src/components/RenderProductsLayout/index.js
src/themes/five/src/components/SingleProductCard/index.js
src/themes/five/src/components/SingleProductCard/styles.js

Story: https://app.asana.com/0/home/1200550251832815/1202857088980537
Demo: https://d.pr/v/R6LZ85

Not show dummy img

---

src/themes/five/src/components/Cart/index.js
src/themes/five/src/components/Cart/styles.js

STORY: https://app.asana.com/0/1198717964402573/1202772001252225

[Add] Coupon and driver tip for multi checkout

---

src/themes/five/src/components/OrderItAgain/styles.js

Story: https://app.asana.com/0/1200268243113852/1202930558714902

Update: orderItAgain

---

src/themes/four/src/components/BusinessBasicInformation/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202908453837463
Demo:  https://d.pr/v/Vu45yH

show searchbar always

---

src/themes/five/src/components/Checkout/styles.js

Story: https://app.asana.com/0/home/1200550251832815/1202786348070189
Demo: https://d.pr/v/Q69PJW

improve checkout style

---

src/themes/five/src/components/Checkout/index.js

STORY: https://app.asana.com/0/1198717964402573/1202786348070187

[Fix] business redirect

---

src/themes/five/src/components/SingleProductCard/index.js
src/themes/five/src/components/SingleProductCard/styles.js

Story: https://app.asana.com/0/home/1200550251832815/1202925008619977
Demo: https://d.pr/v/clDmz6

add style for button in singleProductCart

---

src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/ProfessionalFilter/index.js
src/themes/five/src/components/ProfessionalFilter/styles.js
src/themes/five/src/components/ServiceForm/index.js
src/themes/five/src/components/ServiceForm/styles.js

Story: https://app.asana.com/0/1200268243113852/1202895119114995

[Update]: Booking

---

src/themes/five/src/components/Cart/index.js

STORY: https://app.asana.com/0/1198717964402573/1202931119467557

[Add] validation for wallets in multi checkout

---

src/themes/five/src/components/OrderDetails/index.js
template/pages/OrderDetails/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202929379818005
Demo: https://d.pr/v/AIcjLp

business logo validation

---

src/themes/five/src/components/MultiCheckout/index.js

STORY: https://app.asana.com/0/1198717964402573/1202946808382776

[Add] warning for having carts related to wallets

---

src/themes/five/src/components/OrderDetails/index.js
src/themes/five/src/components/OrderDetails/styles.js

Story; https://app.asana.com/0/home/1200550251832815/1202786348070191
Demo: https://d.pr/v/V6EyjA

improve order detail style

---

src/themes/five/src/components/SignUpApproval/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202914971369523

fix import statement

---

src/themes/five/src/components/OrderDetails/styles.js

Story: https://app.asana.com/0/home/1200550251832815/1202848502471970
Demo:  https://d.pr/v/7S2ijH

update order detail style

---

src/components/AutoScroll/styles.js
src/themes/five/src/components/BusinessController/styles.js

Story: https://app.asana.com/0/home/1200550251832815/1202942045810954
Demo: https://d.pr/v/SgQppE

fix store page responsive

---

src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js
src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/styles.js

STORY: https://app.asana.com/0/1198717964402573/1202934813272525

Feedback template 5

---

src/themes/five/src/components/LoginForm/index.js
src/themes/five/src/components/SignUpBusiness/layouts/NewSignUpBusiness/index.js
src/themes/five/src/components/SignUpBusiness/layouts/OldSignUpBusiness/index.js
src/themes/five/src/components/SignUpDriver/layouts/NewSignUpDriver/index.js
src/themes/five/src/components/SignUpDriver/layouts/OldSignUpDriver/index.js
src/themes/five/src/components/SignUpForm/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202909265940554

Add recaptchav3

---

src/themes/five/src/components/RenderProductsLayout/index.js

STORY: https://app.asana.com/0/1198717964402573/1202946808382762

[Fix] loading issue

---

src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js

STORY: https://app.asana.com/0/1198717964402573/1203005671215213

[Fix] crash error

---

src/themes/five/src/components/ProductForm/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202905969977217
Demo: https://d.pr/v/UyxOl8

improvement max product

---

src/themes/five/index.js
src/themes/five/src/components/BusinessBasicInformation/index.js
src/themes/five/src/components/BusinessProductsCategories/index.js
src/themes/five/src/components/BusinessProductsCategories/styles.js
src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/BusinessProductsListing/styles.js
src/themes/five/src/components/MyOrders/index.js
src/themes/five/src/components/OrderDetails/index.js
src/themes/five/src/components/ProfessionalBusinessFilter/index.js
src/themes/five/src/components/ProfessionalBusinessFilter/styles.js
src/themes/five/src/components/ProfessionalFilter/index.js
src/themes/five/src/components/ProfessionalFilter/styles.js
src/themes/five/src/components/ProfessionalInfo/index.js
src/themes/five/src/components/ProfessionalInfo/styles.js
src/themes/five/src/components/RenderProductsLayout/index.js
src/themes/five/src/components/RenderProductsLayout/styles.js
src/themes/five/src/components/ReviewProfessional/index.js
src/themes/five/src/components/ReviewProfessional/styles.js
src/utils/index.js

Story: https://app.asana.com/0/1200268243113852/1202940559411904

Booking feedback

---

src/hooks/useRecaptcha.js
src/themes/five/src/components/LoginForm/index.js
src/themes/five/src/components/SignUpBusiness/layouts/NewSignUpBusiness/index.js
src/themes/five/src/components/SignUpBusiness/layouts/OldSignUpBusiness/index.js
src/themes/five/src/components/SignUpDriver/layouts/NewSignUpDriver/index.js
src/themes/five/src/components/SignUpDriver/layouts/OldSignUpDriver/index.js
src/themes/five/src/components/SignUpForm/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202909265940554

bug recaptcha v3

---

src/themes/five/src/components/ProductForm/index.js

story: https://app.asana.com/0/home/1200550251832815/1203032403827243
Demo: https://d.pr/v/Kqsy97

improvement product max amount

---

src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/ProductShare/ProductCopyURL.js
src/themes/five/src/components/ProductShare/index.js
src/themes/five/src/components/ProductShare/styles.js

STORY: https://app.asana.com/0/1198717964402573/1203006618554105

[Add] custom product copy URL

---

src/themes/five/src/components/ProductForm/index.js

Story: https://app.asana.com/0/home/1200550251832815/1203056842617212
Demo: https://d.pr/v/uPRAnt

improvement max quantity

---

src/themes/five/index.js
src/themes/five/src/components/NavigationBar/index.js
src/themes/five/src/components/NavigationBar/styles.js

Story: https://app.asana.com/0/home/1200550251832815/1202934656835252

add bottom menu

---

src/themes/five/src/components/BusinessListingSearch/index.js
src/themes/five/src/components/OrdersOption/PreviousBusinessOrdered/index.js
src/themes/five/src/components/OrdersOption/index.js

Reverts Ordering-Inc/Ordering-UI#1309

Revert "[FIX] improvements 19 sept"

---

src/themes/five/src/components/SingleProductCard/styles.js

Story: https://app.asana.com/0/1200268243113852/1203068353973198

Update: ribbon text

---

src/themes/five/src/components/BusinessProductsList/index.js
src/themes/five/src/components/BusinessProductsList/styles.js

Story: https://app.asana.com/0/1200268243113852/1203047858590468

Update: subcategory scroll

---

src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js
yarn.lock

STORY: https://app.asana.com/0/inbox/1198717964396322/1202934750595391/1202942027638971

[update] business listing hero height by theme

---

src/themes/five/src/components/SearchProducts/index.js

STORY: https://app.asana.com/0/1198717964402573/1203129853422958

[Fix] search products for parent categories use

---

src/themes/five/src/components/Checkout/index.js

Story: https://app.asana.com/0/1202730588051168/1203151778536536/f
Video: https://d.pr/v/Keuip3

[FEAT] Ubercash feedback fix

---

src/themes/five/src/components/ReviewProduct/index.js
template/app.js

Story: https://app.asana.com/0/1200268243113852/1203081113895997

[Update]: product review

---

src/themes/five/src/components/ProductItemAccordion/index.js
src/themes/five/src/components/ProductItemAccordion/styles.js

Story: https://app.asana.com/0/1200268243113852/1203152751904161

Update: time range on Cart

---

src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/SingleProductCard/index.js

Story: https://app.asana.com/0/1200268243113852/1203144781893972

[Update]: max amount of product

---

src/components/PaymentOptions/index.js
src/themes/five/src/components/PaymentOptions/index.js

demo template 5: https://www.loom.com/share/010d03255b354499af15b68d4bdce058
demo template 1: https://www.loom.com/share/b3f774fd25004f56a0579dfbe33dee25

[Fix] paymethod did not refresh when change delivery type

---

src/themes/five/src/components/MyOrders/index.js

demo: https://www.loom.com/share/df6a9f09f5ec407db56e8a7b52ae81f4

[Fix] showing divider when there is not data

---

src/themes/five/src/components/Checkout/index.js

demo: https://www.loom.com/share/87cbee215f9f402e9e60ab21ced94901

Table order mandatory

---

src/themes/five/src/components/BusinessListingSearch/index.js

Story: https://app.asana.com/0/1199511033583011/1203050493058927/f
Video: https://d.pr/v/fXKvrG

[FEAT] added auto load more at buttom page

---

src/themes/five/src/components/BusinessListingSearch/index.js

Noticed the missed spelled text

[FEAT] fix crash

---

src/components/LoginForm/index.js
src/components/SignUpForm/index.js
src/themes/callcenterOriginal/src/components/LoginForm/index.js
src/themes/callcenterOriginal/src/components/SignUpForm/index.js
src/themes/eight/src/components/LoginForm/index.js
src/themes/eight/src/components/SignUpForm/index.js
src/themes/four/src/components/LoginForm/index.js
src/themes/four/src/components/LoginForm/styles.js
src/themes/four/src/components/SignUpForm/index.js
src/themes/four/src/components/SignUpForm/styles.js
src/themes/franchise/src/components/LoginForm/index.js
src/themes/franchise/src/components/SignUpForm/index.js
src/themes/seven/src/components/LoginForm/index.js
src/themes/seven/src/components/SignUpForm/index.js
src/themes/six/src/components/LoginForm/index.js
src/themes/six/src/components/SignUpForm/index.js
src/themes/three/src/components/LoginForm/index.js
src/themes/three/src/components/LoginForm/styles.js
src/themes/three/src/components/SignUpForm/index.js
src/themes/three/src/components/SignUpForm/styles.js
src/themes/two/src/components/LoginForm/index.js
src/themes/two/src/components/SignUpForm/index.js

Story: https://app.asana.com/0/1200268243113852/1203205055762104

Update: login and update recaptcha

---

src/themes/five/src/components/ServiceForm/index.js

Story: https://app.asana.com/0/inbox/1200268243109536/1203219557708512/1203227580341509

Update: Wrong api

---

src/styles/Switch/index.js
src/styles/Switch/styles.js
src/themes/five/index.js
src/themes/five/src/components/UserFormDetails/index.js
src/themes/five/src/components/UserFormDetails/styles.js
src/themes/five/src/components/UserProfileForm/index.js

demo: https://www.loom.com/share/9a911d9ee0694ceb830cf13bdb1d5ef0

[Add] enable/disable marketing notifications

---

src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/ProductForm/index.js

STORY: https://app.asana.com/0/1198717964402573/1203237025908925

[Update] minimum order instead of maximum order

---

src/themes/five/src/components/OrderDetails/OrderActionsSection.js
src/themes/five/src/components/OrderDetails/OrderHeaderInfoSection.js
src/themes/five/src/components/OrderDetails/index.js

[FIX] driver location when is string, show driver map if is original layout

---

src/themes/five/src/components/OrderDetails/index.js
src/themes/five/src/components/OrderDetails/styles.js

Story: https://app.asana.com/0/1200268243113852/1203249106622827

Order detail

---

src/themes/five/src/components/OrderDetails/index.js

STORY: https://app.asana.com/0/1198717964402573/1203254334997751

[Add] order status button validation

---

src/components/LoginForm/index.js
src/components/SignUpForm/index.js
src/themes/callcenterOriginal/src/components/LoginForm/index.js
src/themes/callcenterOriginal/src/components/SignUpForm/index.js
src/themes/eight/src/components/LoginForm/index.js
src/themes/eight/src/components/SignUpForm/index.js
src/themes/four/src/components/LoginForm/index.js
src/themes/four/src/components/SignUpForm/index.js
src/themes/franchise/src/components/LoginForm/index.js
src/themes/franchise/src/components/SignUpForm/index.js
src/themes/seven/src/components/LoginForm/index.js
src/themes/seven/src/components/SignUpForm/index.js
src/themes/six/src/components/LoginForm/index.js
src/themes/six/src/components/SignUpForm/index.js
src/themes/three/src/components/LoginForm/index.js
src/themes/three/src/components/SignUpForm/index.js

Story: https://app.asana.com/0/1200268243113852/1203247492013434

[Update]: recaptch for login

---

src/themes/five/src/components/Cart/index.js
src/themes/five/src/components/ServiceForm/index.js
src/themes/five/src/components/ServiceForm/styles.js

Story: https://app.asana.com/0/1200268243113852/1203219557708512

[Update]: booking order

---

src/themes/five/src/components/OrderDetails/index.js
src/themes/five/src/components/OrderDetails/styles.js

Story: https://app.asana.com/0/1200268243113852/1203279260800812

Update: order detail

---

src/themes/callcenterOriginal/src/components/Header/styles.js

demo: https://www.loom.com/share/e89a985e4f1a4f0186c69cc9c5e5165e

[Fix] far away message were overlaped

---

src/themes/five/src/components/BusinessProductsCategories/layouts/groceries/styles.js
src/themes/five/src/components/CartPopover/styles.js
src/themes/five/src/components/RenderProductsLayout/index.js

demos are in every task's comments

Web issues

---

src/themes/five/src/components/BusinessBasicInformation/index.js
src/themes/five/src/components/BusinessBasicInformation/styles.js
src/themes/five/src/components/BusinessController/index.js
src/themes/five/src/components/BusinessController/styles.js
src/utils/index.js

Story: https://app.asana.com/0/1199511033583011/1202981744942144/f
Image: https://d.pr/i/37jdxs

[FEAT] color contrast text depending on brightness

---

src/themes/five/src/components/Checkout/index.js
src/themes/five/src/components/Checkout/styles.js

Story: https://app.asana.com/0/1199511033583011/1203294349468413/f
Video: https://d.pr/v/0qgZmt

[FEAT] design improvement

---

src/themes/five/src/components/BusinessProductsListing/index.js
template/app.js

demo: https://www.loom.com/share/ce6cc2a77954449b816648886936b244

[Fix] show review orden after login when adding a product

---

src/themes/five/src/components/BusinessListingSearch/index.js

Story: https://app.asana.com/0/1199511033583011/1203050493058927/f
Image: https://d.pr/i/BbepTQ

[FEAT] Show all business

---

src/themes/five/src/components/SignUpApproval/index.js
template/app.js
template/config.json

story: https://app.asana.com/0/1203068399720324/1203297670470070
demo: https://www.loom.com/share/97714acd3f6d429681c260286cbd3379

[Add] config dashboard url

---

src/themes/five/src/components/OrdersOption/PreviousBusinessOrdered/index.js
src/themes/five/src/components/OrdersOption/index.js

STORY: https://app.asana.com/0/1198717964402573/1203325383180283

[Fix] business favorite issue

---

src/themes/five/src/components/BusinessBasicInformation/index.js
src/themes/five/src/components/Header/index.js
src/themes/five/src/components/Header/styles.js
src/themes/five/src/components/PaymentOptions/index.js

story: https://app.asana.com/0/1203068399720324/1203301857571549
note: demos are in every task's comments

Web improvements

---

src/themes/five/src/components/OrderDetails/index.js

STORY: https://app.asana.com/0/1198717964402573/1203318610610317

[Update] Order share URL Style

---

src/themes/five/src/components/HomeHero/layouts/OriginalHomeHero/index.js

story: https://app.asana.com/0/1203068399720324/1203363544092760
demo: https://www.loom.com/share/7262c6e7322a4bc2b2bb87fcb0a18c87

[Add] language variables for login/signup

---

src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js
src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/styles.js
src/themes/five/src/components/Header/index.js
template/app.js
template/components/HelmetTags/index.js

Story: https://app.asana.com/0/1200268243113852/1203305758297330

[Update]: theme settings

---

src/themes/five/src/components/OrderDetails/OrderBillSection.js

story: https://app.asana.com/0/1203068399720324/1203363544092787
demo: https://www.loom.com/share/fa82150ac6864e0883a2ed5763d7c581

[Fix] cash language variable

---

src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js

story: https://app.asana.com/0/1203068399720324/1203372154371233
demo: https://www.loom.com/share/357ec552b4d1416ba26fafe8b0faf1e0

[Fix] order types in mobile web version

---

src/themes/five/src/components/BusinessProductsCategories/layouts/groceries/styles.js

story: https://app.asana.com/0/1203068399720324/1203269656796733
demo: https://www.loom.com/share/8ab50173f69d478790be3a7750f357b2

[Fix] sort box overlaps float categories

---

src/themes/five/index.js
src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js
src/themes/five/src/components/PageBanner/index.js
src/themes/five/src/components/PageBanner/styles.js
src/themes/five/src/components/RenderProductsLayout/index.js
src/themes/five/src/components/RenderProductsLayout/styles.js
template/pages/Home/index.js

STORY: https://app.asana.com/0/1198717964402573/1201184519566877

[Feat] Project banner

---

src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js

Story: https://app.asana.com/0/1200268243113852/1203305758297330

Update: business image settings

---

src/components/BusinessInformation/index.js

story: https://app.asana.com/0/1203068399720324/1203347054300222
demo: https://www.loom.com/share/8b412a1f2dad4aa09b475902657ca798

[Fix] schedule format

---

src/themes/five/src/components/BusinessPreorder/index.js
src/themes/five/src/components/MomentControl/index.js
src/themes/five/src/components/ProductItemAccordion/index.js
src/themes/five/src/components/ProfessionalProfile/index.js
src/themes/five/src/components/ServiceForm/index.js
src/themes/five/src/components/ServiceForm/styles.js
src/utils/index.js

Story: https://app.asana.com/0/1200268243113852/1203350658756733

Update: cart edit

---

src/themes/five/src/components/InputPhoneNumber/index.js
src/themes/five/src/components/LoginForm/index.js
src/themes/five/src/components/SignUpForm/index.js

story: https://app.asana.com/0/1199511033583011/1203356521137926/f
demo Web: https://www.loom.com/share/c706d4223d624c1ab517842194c65d21

[Update] turn on auto complete email and phone

---

src/themes/five/src/components/OrderDetails/index.js
src/themes/five/src/components/OrderDetails/styles.js
src/themes/five/src/components/PlaceSpot/styles.js

STORY: https://app.asana.com/0/1198717964402573/1203318610610317

[Fix] spot responsive issue

---

src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/SingleProductCard/layouts/original/styles.js

story: https://app.asana.com/0/1199511033583011/1203345179111237/f
demo: https://www.loom.com/share/b324899de05441478dd419e9310f1308

[Add] implement add product one click

---

src/themes/five/src/components/HomeHero/layouts/OriginalHomeHero/index.js

Story: https://app.asana.com/0/1200268243113852/1203449320720243

[Add]: home page mobile image from theme

---

src/themes/five/src/components/Checkout/index.js
src/themes/five/src/components/PlaceSpot/index.js

story: https://app.asana.com/0/0/1203462140613951/f
demo Web: https://www.loom.com/share/412fe00990e2415db288a27cee382679

[Update] save table number with place order

---

src/themes/five/src/components/Checkout/index.js

story: https://app.asana.com/0/0/1203493790707924/f
demo: https://www.loom.com/share/030ed9dd53444d29ac7bea6981cb8aa3

[Add] config for enable/disable table number requirement

---

src/themes/five/src/components/PhoneAutocomplete/index.js

story: https://app.asana.com/0/0/1203516403941670/f
demo: https://www.loom.com/share/c0ba96d240764da4b89e13cf345d2bac

call center feedback

---

src/themes/five/src/components/OrderDetails/index.js
src/themes/five/src/components/OrderProgress/index.js
src/themes/five/src/components/SingleOrderCard/index.js

STORY: https://app.asana.com/0/1198717964402573/1202956130057095

[Add] ETA's functionality

---

src/themes/five/src/components/BusinessesListing/layouts/StarbucksBusinessesListing/index.js
src/themes/five/src/components/BusinessesListing/layouts/StarbucksBusinessesListing/styles.js
src/themes/five/src/components/ProductForm/styles.js
src/themes/five/src/components/ProductOptionSubOption/styles.js
src/themes/six/src/components/BusinessController/styles.js
src/themes/six/src/components/SearchBar/index.js
src/themes/six/src/components/SearchBar/styles.js

story: https://app.asana.com/0/0/1203516121937780/f

Starbucks feedback

---

src/themes/five/src/components/OrderDetails/OrderBillSection.js

story: https://app.asana.com/0/1199511033583011/1203534447734713/f
demo Web: https://prnt.sc/CzlRkBdHTfnS

[Fix] paymethods key_langs

---

src/themes/five/src/components/Cart/index.js

Story: https://app.asana.com/0/1199511033583011/1203428923672622/f
Video: https://d.pr/v/ynPhQo

[FEAT] fix-offers-call-center

---

src/themes/five/index.js
src/themes/five/src/components/BusinessInformation/index.js
src/themes/five/src/components/ScheduleAccordion/index.js
src/themes/five/src/components/ScheduleAccordion/styles.js

story: https://app.asana.com/0/1199511033583011/1203515954285876/f
demo Web: https://prnt.sc/a-OMLZtIwf16

[Update] schedule slots design

---

src/themes/pwa/src/components/MomentContent/index.js

story: https://app.asana.com/0/1199511033583011/1203537128769447/f
demo: https://www.loom.com/share/ef396f0b916a4178b9d9a2478f098e66

[Fix] pwa bug when business is closed

---

src/themes/five/src/components/BusinessProductsList/index.js

story: https://app.asana.com/0/1199511033583011/1203574840571908/f
demo: https://www.loom.com/share/7a5b613b96394a34832c98ea61d73688

[Add] more button for all category products list

---

src/themes/five/src/components/ReviewProduct/index.js

story: https://app.asana.com/0/1199511033583011/1203537128769434/f
demo: https://www.loom.com/share/209d9420e1c047d1ad56fb2f7df279c4

[Fix] crash after review a product

---

src/themes/pwa/src/components/MomentContent/index.js
src/themes/pwa/src/components/MomentControl/index.js

story: https://app.asana.com/0/1199511033583011/1203537128769447/f
demo: https://www.loom.com/share/b11ea0fd4f954a61834b210bd42a8608

[Fix] asap button went blank

---

src/themes/callcenterOriginal/src/components/Orders/OrderContactInformation/index.js
src/themes/callcenterOriginal/src/components/Orders/OrdersTable/index.js

Story: https://app.asana.com/0/0/1203580113207983/f
Video: https://d.pr/v/H3wPNL

[FEAT] fix-order-column-filter

---

src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/ServiceForm/index.js

Story: https://app.asana.com/0/1200268243113852/1203580203471885

[Fix]: professional times

---

src/themes/callcenterOriginal/src/components/Orders/OrdersTable/index.js
src/themes/callcenterOriginal/src/components/Orders/OrdersTable/styles.js

Story: https://app.asana.com/0/0/1203607722115175/f

[FEAT] fix design filter columns call center

---

src/themes/five/src/components/BusinessProductsList/index.js

story: https://app.asana.com/0/0/1203587683406769/f
demo: https://www.loom.com/share/2e02e19c98ef4cc08f4580db793fd960

[Add] more button to subcategories

---

src/themes/five/src/components/OrderDetails/index.js

story: https://app.asana.com/0/1199511033583011/1203562433945799/f
demo: https://www.loom.com/share/5d5b2b28215f438bbd5a88521eae6a4b

-[Fix] order details were able to modify after complete

---

src/themes/five/src/components/ProductItemAccordion/index.js
src/themes/five/src/components/ProductItemAccordion/styles.js

STORY: https://app.asana.com/0/1198717964402573/1203580203471878

allow to remove the  invalid product

---

src/themes/five/src/components/BusinessListingSearch/index.js
src/themes/five/src/components/ProductForm/index.js

story: https://app.asana.com/0/1199511033583011/1203582422462680/f
demo: https://www.loom.com/share/73789b84518a4dc8b0602e47a842ac68

[Fix] minimun to order on product form from search

---

src/components/VerticalOrdersLayout/SingleOrderCard/index.js
src/components/VerticalOrdersLayout/styles.js
src/themes/five/src/components/OrdersOption/index.js

story: https://app.asana.com/0/1199511033583011/1203626345903107/f
demo: https://www.loom.com/share/7552798c0ae0421bb5b558dde0527dd3

[Add] open past orders

---

src/themes/five/src/components/OrderDetails/index.js

story: https://app.asana.com/0/0/1203640886842526/f

[Add] status for block buttons in pick up

---

src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js
src/themes/five/src/components/HorizontalOrdersLayout/index.js

Reverts Ordering-Inc/Ordering-UI#1491

Revert "[ADD] callcenter improvements"

---

src/themes/five/src/components/SingleProductCard/layouts/original/index.js
src/themes/five/src/components/SingleProductCard/layouts/original/styles.js

Story: https://app.asana.com/0/1199511033583011/1203511965605503/f

[FEAT] show product tags in single card

---

src/themes/five/src/components/CartContent/index.js

Story: https://app.asana.com/0/0/1203689096386616/f

[FEAT] fix multicheckout when new user

---

src/themes/five/src/components/OrderDetails/OrderEta.js
src/themes/five/src/components/OrderDetails/index.js
src/themes/five/src/components/OrderProgress/index.js
src/themes/five/src/components/SingleOrderCard/index.js

STORY: https://app.asana.com/0/1198717964402573/1203547429694268

[Update] ETA's functionality

---

src/themes/five/src/components/PageBanner/index.js
src/themes/five/src/components/PageBanner/styles.js

STORY: https://app.asana.com/0/1198717964402573/1203617107794972

[Add] banner link functionality

---

src/themes/five/src/components/Checkout/index.js
src/themes/five/src/components/OrderItAgain/styles.js

story: https://app.asana.com/0/1199511033583011/1203587132625857/f
demo: https://d.pr/v/32mPkG

place order button in mobile were active when no payment selected

---

src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/ProfessionalFilter/index.js
src/themes/five/src/components/ProfessionalFilter/styles.js
src/themes/five/src/components/RenderProductsLayout/index.js
src/themes/five/src/components/ServiceForm/index.js
src/themes/five/src/components/ServiceForm/styles.js
src/themes/five/src/components/SingleProfessionalCard/index.js
src/themes/five/src/components/SingleProfessionalCard/styles.js

STORY: https://app.asana.com/0/1198717964402573/1203658063963189

[Update] Appointments functionality

---

src/themes/five/src/components/SingleProductCard/layouts/original/index.js
src/themes/five/src/components/SingleProductCard/layouts/original/styles.js

Story: https://app.asana.com/0/0/1203713407743882/f
Video: https://d.pr/v/sgbGfb

[FEAT] improve-show-tags-scrollable

---

src/themes/five/src/components/Cart/index.js
src/themes/five/src/components/PaymentOptions/index.js
src/themes/five/src/components/PaymentOptions/styles.js

story: https://app.asana.com/0/1199511033583011/1203630157670094/f

Qa web app fixes

---

src/themes/five/src/components/DriverTips/index.js

story: https://app.asana.com/0/1199511033583011/1203713044564795/f
demo: https://d.pr/v/D3US59

[Update] custon tips as an additional option

---

src/themes/five/src/components/OrderDetails/index.js

story: https://app.asana.com/0/1199511033583011/1203640886842530/f

[Fix] pick up options were showing in delivey

---

src/themes/five/src/components/OrderDetails/OrderEta.js

STORY: https://app.asana.com/0/1198717964402573/1203760906631922

[Update] ETA for order status penalty times

---

src/themes/five/src/components/ProductOptionSubOption/index.js

Story: https://app.asana.com/0/1200268243113852/1203773573185094

[Bug]: product suboption warning message

---

package.json
src/themes/five/src/components/Checkout/index.js
src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/ProductForm/styles.js
src/themes/five/src/components/ServiceForm/index.js
src/themes/five/src/components/ServiceForm/styles.js
src/themes/five/src/components/SignUpForm/index.js
src/themes/five/src/components/UserFormDetails/index.js
src/themes/five/src/components/UserFormDetails/styles.js
src/utils/index.js
yarn.lock

Story: https://app.asana.com/0/1200268243113852/1202884440279618

[Feat]: Guest checkout

---

src/themes/five/src/components/OrderDetails/index.js
src/themes/five/src/components/OrderDetails/styles.js

story: https://app.asana.com/0/0/1203759160816749/f

[Fix] business information in order details

---

src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/PageBanner/index.js

STORY: https://app.asana.com/0/1198717964402573/1203790174022632

[Fix] product banner click issue

---

src/themes/five/src/components/Checkout/index.js
src/themes/five/src/components/MultiCheckout/index.js

Story: https://app.asana.com/0/1199511033583011/1203763934662242/f

[FEAT] change checkout variable

---

src/themes/pwa/src/components/MomentControl/index.js
src/utils/index.js

story: https://app.asana.com/0/1199511033583011/1203766516531416/f

[Fix] key_langs for mobile web

---

src/themes/five/src/components/BusinessPreorder/index.js
src/themes/five/src/components/BusinessPreorder/styles.js
src/themes/five/src/components/ServiceForm/index.js
src/themes/five/src/components/ServiceForm/styles.js

STORY: https://app.asana.com/0/1198717964402573/1203698455623960

[Add] Schedule color

---

src/themes/five/src/components/WalletTransactionItem/index.js

story: https://app.asana.com/0/1199511033583011/1203790302222655/f

[Add] key_langs for wallet sections

---

src/themes/five/src/components/Checkout/index.js
src/themes/five/src/components/DriverTips/index.js
src/themes/five/src/components/MultiCheckout/index.js

story: https://app.asana.com/0/1199511033583011/1203713044564795/f

[Fix] custom driver tips for multi business checkout

---

src/themes/five/src/components/OrderDetails/OrderEta.js

story: https://app.asana.com/0/1199511033583011/1203858852403669/f

[Fix] invalid date format in eta funcionality

---

src/themes/five/src/components/Checkout/index.js
src/themes/five/src/components/Checkout/styles.js
src/themes/five/src/styles/Buttons/index.js

Story: https://app.asana.com/0/1200268243113852/1203803620267194

[Update]: Imporve guest checkout

---

src/hooks/useIntersectionObserver.js

story: https://app.asana.com/0/1199511033583011/1203713044564740/f

[Fix] skeleton issue in productlist

---

src/themes/callcenterOriginal/src/components/Header/index.js

Story: https://app.asana.com/0/1203665030940611/1203861647278719/f
Video: https://d.pr/v/jZ5zw1

[FEAT] show preorder option call center

---

src/themes/five/src/components/Messages/index.js

story: https://app.asana.com/0/1199511033583011/1203827976826203/f

[Fix] do not show suggestions after order ends

---

src/components/PaymentOptions/index.js

story: https://app.asana.com/0/1199511033583011/1203871219905584/f

[Fix] driver tip when pay with paypal

---

src/components/VerticalOrdersLayout/styles.js
src/themes/five/src/components/AddressList/index.js
src/themes/five/src/components/CardForm/index.js
src/themes/five/src/components/Checkout/index.js
src/themes/five/src/components/Checkout/styles.js
src/themes/five/src/components/Header/index.js
src/themes/five/src/components/Header/styles.js
src/themes/five/src/components/MultiCartsPaymethodsAndWallets/index.js
src/themes/five/src/components/MultiCheckout/index.js
src/themes/five/src/components/OrderContextUI/index.js
src/themes/five/src/components/OrderContextUI/styles.js
src/themes/five/src/components/OrderDetails/index.js
src/themes/five/src/components/PaymentOptionStripe/index.js
src/themes/five/src/components/PaymentOptionStripe/styles.js
src/themes/five/src/components/PaymentOptions/index.js
src/themes/five/src/components/SidebarMenu/index.js

story: https://app.asana.com/0/1199511033583011/1203802187527538/f

Feedback jan 25

---

src/themes/five/src/components/MyOrders/styles.js

story: https://app.asana.com/0/1199511033583011/1203912605330197/f

[Fix] footer overlaps when there is not orders in my order section

---

src/themes/five/src/components/BusinessProductsListing/index.js
template/app.js

story: https://app.asana.com/0/1199511033583011/1203932548529396/f

[Fix] marketplace redirect

---

src/themes/five/src/components/Header/index.js

Story: https://app.asana.com/0/1200268243113852/1203952056650299

[Update]: Bugs del website setup

---

src/themes/callcenterOriginal/index.js

Story: https://app.asana.com/0/1203820777812437/1203968795759739/f

[FEAT] add missing export for theme callcenter

---

src/themes/callcenterOriginal/index.js

Reverts Ordering-Inc/Ordering-UI#1565

Revert "[FEAT] add missing export for theme callcenter"

---

src/themes/five/src/components/OrderDetails/OrderEta.js
src/themes/five/src/components/OrderProgress/index.js

story: https://app.asana.com/0/1199511033583011/1203968315529023/f

[Fix] progress section invalid date

---

src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/PageBanner/index.js

STORY: https://app.asana.com/0/1198717964402573/1203978272594919

[Update] Banners go back availability

---

src/themes/five/src/components/Header/index.js
src/themes/five/src/components/HomeHero/layouts/OriginalHomeHero/index.js

Story: https://app.asana.com/0/1199511033583011/1203980687958554/f

[FEAT] change logo for web mobile

---

src/themes/five/src/components/PageBanner/styles.js

STORY: https://app.asana.com/0/1198717964402573/1203988893191032

[Fix] banner responsive

---

src/themes/five/src/components/OrderDetails/OrderEta.js

STORY: https://app.asana.com/0/1198717964402573/1204053298611733

[Fix] order time issue

---

src/themes/five/src/components/ProductItemAccordion/index.js

Story: https://app.asana.com/0/1200268243113852/1204070506706104

[Update]: remove trash symbol

---

src/themes/five/src/components/AddressList/index.js
src/themes/five/src/components/BusinessBasicInformation/index.js
src/themes/five/src/components/BusinessBasicInformation/styles.js
src/themes/five/src/components/BusinessListingSearch/index.js
src/themes/five/src/components/BusinessListingSearch/styles.js
src/themes/five/src/components/BusinessProductsCategories/index.js
src/themes/five/src/components/BusinessProductsCategories/styles.js
src/themes/five/src/components/BusinessProductsList/index.js
src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/BusinessProductsListing/styles.js
src/themes/five/src/components/Checkout/index.js
src/themes/five/src/components/Checkout/styles.js
src/themes/five/src/components/OrderItAgain/styles.js
src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/ProductForm/styles.js
src/themes/five/src/components/RenderProductsLayout/index.js
src/themes/five/src/components/SingleOrderCard/styles.js
src/themes/five/src/components/SingleProductCard/layouts/original/styles.js
src/themes/five/src/components/UpsellingPage/index.js

STORY: https://app.asana.com/0/1198717964402573/1203968481752187

Website feedback

---

src/themes/five/src/components/BusinessListingSearch/index.js
src/themes/five/src/components/MyOrders/index.js
src/themes/five/src/components/MyOrders/styles.js

STORY: https://app.asana.com/0/1198717964402573/1204089619700606

[Fix] space issue

---

src/themes/five/src/components/Cart/index.js
src/themes/five/src/components/Checkout/index.js

Story: https://app.asana.com/0/1199511033583011/1204008411469418/f

[FEAT] validation-cart-comment-field

---

src/components/OrdersOption/styles.js
src/components/VerticalOrdersLayout/styles.js
src/themes/five/src/components/Checkout/styles.js

Story: https://app.asana.com/0/1199511033583011/1204008411469415/f

[FEAT] fix mobile checkout

---

src/themes/five/src/components/Checkout/index.js

Story: https://app.asana.com/0/0/1204098917419659/f

[FEAT] fix address checkout change map

---

src/themes/five/src/components/BusinessListingSearch/styles.js
src/themes/five/src/components/RenderProductsLayout/index.js

STORY: https://app.asana.com/0/1198717964402573/1204101248174181

[Fix] Feedback template 5

---

src/themes/five/src/components/AddressList/index.js
src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/ProductItemAccordion/index.js

Story: https://app.asana.com/0/1200268243113852/1203937977290051

[Update]: Guest checkout feedback

---

src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js
src/themes/five/src/components/CitiesControl/index.js

Story: https://app.asana.com/0/1200268243113852/1204106130196035

[Update]: country filter

---

src/components/UserProfileForm/index.js

STORY: https://app.asana.com/0/1198717964402573/1204090004475586

[Fix] name space issue

---

src/themes/five/src/components/MultiOrdersDetails/SingleOrderCard.js

Story: https://app.asana.com/0/1203637309747495/1204098924039220/f
Video: https://d.pr/v/R7MHsx

[FEAT] fix eta times

---

src/themes/five/src/components/OrderDetails/index.js

story: https://app.asana.com/0/1201894042190305/1204125195914046/f

[Fix] preorder status for eta

---

src/themes/five/src/components/OrderDetails/OrderEta.js
src/themes/five/src/components/OrderProgress/index.js

STORY: https://app.asana.com/0/1198717964402573/1204108122124103

[Fix] ETA time issue

---

src/themes/five/src/components/OrderDetails/OrderEta.js

Story: https://app.asana.com/0/1201894042190305/1204125948884226/f
Video: https://d.pr/v/CTJRk1

[FEAT] add-delivered-in-eta-time

---

src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js

Story: https://app.asana.com/0/0/1204138226042327/f

[FEAT] home hero feedback

---

src/themes/five/src/components/OrderProgress/index.js

Story: https://app.asana.com/0/1201894042190305/1204126904626464/f
Video: https://d.pr/v/YiwHvG

[FEAT] fix order in progress for pickup

---

src/themes/five/src/components/ProductOptionSubOption/index.js

Story: https://app.asana.com/0/home/1200268243109536/1204080321263252

[Update]: product suboption preselect

---

src/themes/five/src/components/BusinessController/index.js
template/pages/BusinessesList/index.js

Story: https://app.asana.com/0/1200268243113852/1204092749362954

[Update]: open preorder popup

---

src/components/SmartAppBanner/index.js
template/theme.json

Story: https://app.asana.com/0/1199511033583011/1204119396827389/f

[FEAT] [FEAT] add default languages

---

src/themes/five/src/components/BusinessProductsListing/styles.js
src/themes/five/src/components/ReviewProduct/index.js

story: https://app.asana.com/0/1201894042190305/1204013908283660/f

[Fix] product review for multi business

---

src/themes/five/src/components/OrderContextUI/index.js

Story: https://app.asana.com/0/1200268243113852/1204149184906260

[Update]: fix preorder on mobile mode

---

src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js

STORY: https://app.asana.com/0/1198717964402573/1204156935744967

[Fix] stores more loading issue

---

src/themes/five/src/components/OrderDetails/OrderHistory.js

story: https://app.asana.com/0/1201894042190305/1204125195914046/f

[Fix] time added by driver in order history

---

src/themes/five/src/components/PaymentOptions/index.js

Story: https://app.asana.com/0/1199511033583011/1204168656644135/f

[FEAT] validate gateway

---

src/themes/five/src/components/BusinessBasicInformation/styles.js

Story: https://app.asana.com/0/1200268243113852/1204140165268411

[Update]: store banner image crop

---

src/themes/five/src/components/PaymentOptions/index.js

story: https://app.asana.com/0/1201894042190305/1204172872279318/f

[Fix] double border in payment options

---

src/themes/five/src/components/OrderDetails/OrderEta.js

Story: https://app.asana.com/0/1201894042190305/1204125948884226/f

[FEAT] feedback

---

src/utils/index.js

story: https://app.asana.com/0/1201894042190305/1204127400067789/f

[Fix] progress bar percentage

---

src/themes/five/src/components/Checkout/index.js
src/themes/five/src/components/UserDetails/index.js

https://app.asana.com/0/1199511033583011/1204169925061772/f

[Fix] checkout crash phone number with country code

---

src/themes/five/src/components/GiftCard/RedeemGiftCard/index.js
src/themes/five/src/components/Wallets/index.js

STORY: https://app.asana.com/0/1198717964402573/1204136960622304

Gift card feedback

---

src/components/VerticalOrdersLayout/index.js
src/themes/five/src/components/OrdersOption/index.js
src/themes/five/src/components/ReviewOrder/styles.js

story: https://app.asana.com/0/1201894042190305/1204013908283660/f

[Fix] refresh list after review process ends

---

src/themes/five/src/components/ProductForm/styles.js

STORY: https://app.asana.com/0/1198717964402573/1204229884654492

Template 5 bugs

---

src/themes/five/src/components/AddressForm/index.js

Story: https://app.asana.com/0/1201894042190305/1204004809608154/f
Video: https://d.pr/v/m2T6HD

[FEAT] update address on chew

---

src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js

story: https://app.asana.com/0/1199511033583011/1204243395870035/f

[Fix] progress bar not displayed

---

src/themes/five/src/components/OrderProgress/index.js

story: https://app.asana.com/0/1199511033583011/1204253761211390/f

[Fix] filter orders for progress bar

---

src/themes/five/src/components/LoginForm/index.js

Story: https://app.asana.com/0/1200268243113852/1204146199887050

[Update]: social login

---

src/themes/five/src/components/AddressForm/index.js

Story: https://app.asana.com/0/1201894042190305/1204004809608154/f

[FEAT] fix update location

---

src/themes/five/src/components/Cart/index.js
src/themes/five/src/components/OrderDetails/OrderBillSection.js

Story: https://app.asana.com/0/1200268243113852/1204156116024900

[Bug]: display delivery fee when price is 0

---

src/themes/five/src/components/BusinessProductsListing/index.js

STORY: https://app.asana.com/0/1198717964402573/1204258284120036

[Fix] Sentry undefined (reading 'filter') issue

---

template/app.js
template/pages/BusinessProductsList/index.js
template/pages/BusinessesList/index.js
template/pages/Checkout/index.js
template/pages/Home/index.js
template/pages/MessagesList/index.js
template/pages/MyOrders/index.js

STORY: https://app.asana.com/0/1198717964402573/1204333149865608

[Add] advanced website theme

---

src/themes/five/src/components/Header/index.js

Story: https://app.asana.com/0/1199511033583011/1204309390495870/f
Image: https://d.pr/i/i0HM6R

[FEAT] show image from builder when mobile view

---

src/themes/five/src/components/BusinessInformation/index.js
src/themes/five/src/components/ScheduleAccordion/index.js

story: https://app.asana.com/0/1199511033583011/1204277077371838/f

[Fix] hour format

---

src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js
src/themes/five/src/components/OrderContextUI/index.js

STORY: https://app.asana.com/0/1198717964402573/1204301635478240

[Fix] order context UI in mobile view

---

src/themes/five/src/components/ProductItemAccordion/index.js

story: https://app.asana.com/0/0/1204393589764418/f

Sort products options

---

src/themes/five/src/components/BusinessPreorder/index.js

STORY: https://app.asana.com/0/1198717964402573/1204393477079081

[Update] time format config

---

src/themes/five/src/components/BusinessBasicInformation/index.js
src/themes/five/src/components/BusinessBasicInformation/styles.js

story: https://app.asana.com/0/1199511033583011/1204384977435544/f

[Add] back button in groceries layout

---

src/themes/five/src/components/OrderDetails/index.js
src/themes/five/src/components/OrderDetails/styles.js

Story: https://app.asana.com/0/1200268243113852/1204323937728663

[Bug]: order time format

---

src/themes/five/src/components/ProductOptionSubOption/styles.js

STORY: https://app.asana.com/0/1198717964402573/1204424360980486

[Fix] sub option image issue

---

src/components/UserProfileForm/styles.js
src/themes/callcenterOriginal/src/components/AddressList/index.js
src/themes/callcenterOriginal/src/components/AddressList/styles.js
src/themes/callcenterOriginal/src/components/Header/index.js
src/themes/callcenterOriginal/src/components/Header/styles.js
src/themes/callcenterOriginal/src/components/UserDetails/index.js
src/themes/callcenterOriginal/src/components/UserDetails/styles.js
src/themes/five/src/components/BusinessController/index.js
src/themes/five/src/components/BusinessInformation/styles.js
src/themes/five/src/components/BusinessItemAccordion/styles.js
src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js
src/themes/five/src/components/PhoneAutocomplete/styles.js
src/themes/five/src/components/ProductForm/styles.js
src/themes/five/src/components/ProductShare/index.js
src/themes/five/src/components/ProductShare/styles.js
src/themes/five/src/components/ScheduleAccordion/styles.js
src/themes/five/src/components/SidebarMenu/index.js
src/themes/five/src/components/SidebarMenu/styles.js
src/themes/five/src/components/TaxInformation/styles.js

story: https://app.asana.com/0/0/1204415569370418/f

[Fix] callcenter feedback

---

src/themes/five/src/components/ResetPassword/index.js

Story: https://app.asana.com/0/1200268243113852/1204433056764209

[Update]: password reset language

---

src/themes/callcenterOriginal/src/components/Header/styles.js
src/themes/callcenterOriginal/src/components/SidebarMenu/index.js
src/themes/callcenterOriginal/src/components/SidebarMenu/styles.js
src/themes/callcenterOriginal/src/components/UserDetails/index.js
src/themes/five/src/components/BusinessInformation/styles.js
src/themes/five/src/components/RenderProductsLayout/index.js
src/themes/five/src/components/SidebarMenu/index.js
src/themes/five/src/components/SidebarMenu/styles.js

story: https://app.asana.com/0/1199511033583011/1204171780232888/f

[Fix] fixes for callcenter

---

src/themes/callcenterOriginal/src/components/SidebarMenu/index.js

story: https://app.asana.com/0/1199511033583011/1204171780232888/f

[Fix] icon import were missing

---

src/themes/five/src/components/BusinessProductsListing/index.js

STORY: https://app.asana.com/0/1198717964402573/1204412434089093

[Fix] product one click issue

---

src/themes/five/src/components/BusinessInformation/index.js
src/themes/five/src/components/BusinessInformation/styles.js
src/themes/five/src/components/Checkout/index.js
template/pages/BusinessProductsList/index.js

STORY: https://app.asana.com/0/1198717964402573/1204412434089100

[Add] store address notes

---

src/themes/five/src/components/BusinessController/index.js

Story: https://app.asana.com/0/1199511033583011/1204451140046475/f

[FEAT] fix

---

src/themes/five/src/components/BusinessInformation/index.js
src/themes/five/src/components/BusinessInformation/styles.js

Story: https://app.asana.com/0/1200268243113852/1204335314395668

[Feat]: delivery zone on business map

---

src/components/BusinessBasicInformation/index.js
src/components/BusinessBasicInformation/styles.js

STORY: https://app.asana.com/0/1198717964402573/1203885525305631

[Update] information icon to text

---

src/themes/five/src/components/BusinessBasicInformation/styles.js

Story: https://app.asana.com/0/0/1204487956763026/f

[FEAT] fix-business-info-title-background

---

src/themes/five/src/components/SignUpForm/index.js

STORY: https://app.asana.com/0/1198717964402573/1204291888461194

[Fix] sentry issue (cannot convert undefined or null to object)

---

src/components/Checkout/index.js
src/components/PaymentOptions/index.js

STORY: https://app.asana.com/0/1198717964402573/1204516247637468

[Add] check validation before select PayPal payment

---

src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/HorizontalOrdersLayout/styles.js
src/themes/five/src/components/ProductForm/styles.js
src/themes/five/src/components/RenderProductsLayout/index.js
src/themes/five/src/components/SearchProducts/styles.js

story: https://app.asana.com/0/1199511033583011/1204487956763052/f

[Update] website improvements

---

src/themes/five/src/components/Checkout/index.js
src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/ProductForm/styles.js
src/themes/five/src/components/UserFormDetails/index.js

Story: https://app.asana.com/0/1200268243113852/1204515252368571

[Update]: guest checkout

---

src/themes/five/src/components/BusinessProductsList/index.js

story: https://app.asana.com/0/1199511033583011/1204487956763052/f

[Fix] icon when no items in business product list searhc

---

src/themes/five/src/components/HomeHero/layouts/OriginalHomeHero/index.js
src/themes/five/src/components/HomeHero/layouts/OriginalHomeHero/styles.js
src/themes/five/src/components/OrderDetails/index.js
src/themes/five/src/components/OrderDetails/styles.js

story: https://app.asana.com/0/1199511033583011/1204536036338217/f

[Fix] style issue in powered by link

---

src/themes/five/src/components/Promotions/index.js

Story: https://app.asana.com/0/inbox/1200268243109536/1204579045201676/1204584917834142

[Update]: promotion search text

---

src/themes/five/src/components/OrderDetails/index.js
src/themes/five/src/components/OrderProgress/index.js
src/utils/index.js

story: https://app.asana.com/0/1201894042190305/1204578864994280/f

[Add] status bar for pick up

---

src/themes/five/src/components/BusinessReviews/index.js
src/themes/five/src/components/UserPopover/index.js

story: https://app.asana.com/0/0/1204566686293742/f

[Fix] theme typos

---

src/themes/five/src/components/PaymentOptions/index.js

story: https://app.asana.com/0/1201894042190305/1204568938745166/f

[Fix] apple pay required field

---

src/themes/five/src/components/GiftCard/RedeemGiftCard/index.js
src/themes/five/src/components/LastOrders/index.js
src/themes/five/src/components/OrderProgress/index.js

STORY: https://app.asana.com/0/1198717964402573/1204591370980134

[Update] Gift cards

---

src/themes/five/src/components/MultiCheckout/index.js
src/themes/five/src/components/MultiCheckout/styles.js

Story: https://app.asana.com/0/1200268243113852/1204566686293728

[Update]: Guest multi checkout

---

src/themes/five/src/components/Header/styles.js

Story: https://app.asana.com/0/1200268243113852/1204633811389462

[Update]: Text overflow

---

src/themes/five/src/components/Checkout/index.js

STORY: https://app.asana.com/0/1198717964402573/1204310480526058

[Fix] Sentry issue

---

src/themes/five/src/components/ProductForm/styles.js

story: https://app.asana.com/0/1199511033583011/1204487956763080/f

[Fix] responsive ammount input

---

src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js
template/theme.json

story: https://app.asana.com/0/0/1203472936168271/f

[Update] remove filter from serach

---

src/themes/six/src/components/OrderTypeSelectorHeader/index.js

story: https://app.asana.com/0/1199511033583011/1204737694575717/f

[Add] lang key for order types in elegant layout

---

package.json
src/themes/five/index.js
src/themes/five/src/components/DatePicker/index.js
src/themes/five/src/components/DatePicker/styles.js
src/themes/five/src/components/UserFormDetails/index.js
src/themes/five/src/components/UserFormDetails/styles.js

story: https://app.asana.com/0/1199511033583011/1204566686293757/f

[Feat] birthdate field

---

src/themes/five/src/components/RenderProductsLayout/index.js

STORY: https://app.asana.com/0/1198717964402573/1204592094895327

[Update] banner for business page

---

src/themes/five/src/components/BusinessItemAccordion/index.js
src/themes/five/src/components/Cart/index.js

STORY: https://app.asana.com/0/1198717964402573/1204758891869332

[Update] gift card cart

---

src/themes/five/src/components/ReviewProduct/index.js

story: https://app.asana.com/0/1199511033583011/1204773957768899/f

Blank screen reviewing product

---

src/themes/five/src/styles/Buttons/index.js

story: https://app.asana.com/0/1199511033583011/1204612290223377/f

[Update] button and text button color

---

src/themes/five/src/components/BusinessProductsListing/index.js

Story: https://app.asana.com/0/1200268243113852/1204771586300616

[Update]: fix product load for subcategory

---

src/themes/five/src/components/BusinessItemAccordion/index.js

STORY: https://app.asana.com/0/1198717964402573/1204786876454775

[Fix] hide change store for gift card cart

---

src/themes/five/src/components/Header/index.js

story: https://app.asana.com/0/1199511033583011/1204612290223377/f

[Fix] change sign up button from anchor to button to take theme changes

---

src/themes/five/src/components/BusinessListingSearch/MaxSectionItem/index.js
src/utils/index.js

Story: https://app.asana.com/0/1199511033583011/1204735396231387/f

Variable-minutes-change

---

src/components/VerticalOrdersLayout/SingleOrderCard/index.js
src/themes/five/src/components/SingleOrderCard/index.js

STORY: https://app.asana.com/0/1198717964402573/1204759012858338

hide review and reorder for gift card order

---

src/themes/five/src/components/OrderProgress/styles.js

story: https://app.asana.com/0/1199511033583011/1204788733539125/f

[Fix] logotype size

---

src/themes/callcenterOriginal/src/components/AdminAreaPopover/index.js
src/themes/callcenterOriginal/src/components/AdminAreaPopover/styles.js
src/themes/callcenterOriginal/src/components/Header/index.js
src/themes/callcenterOriginal/src/components/Header/styles.js

Story: https://app.asana.com/0/1199511033583011/1204797384821475/f

[FEAT] fix-header-admin-popup-callcenter

---

src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js
src/themes/five/src/components/RenderProductsLayout/index.js

STORY: https://app.asana.com/0/1198717964402573/1204785506263619

Show Banner for call center

---

src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js
src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/styles.js

story: https://app.asana.com/0/1199511033583011/1204811239492077/f

[Fix] change address button not working

---

src/themes/five/src/components/PageBanner/index.js

STORY: https://app.asana.com/0/1198717964402573/1204843403518262

[Update] hide arrow for one banner

---

src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js
src/themes/five/src/components/PageBanner/index.js
src/themes/five/src/components/RenderProductsLayout/index.js

STORY: https://app.asana.com/0/1198717964402573/1204843278285996

[Fix] Banner call center feedback

---

src/themes/five/src/components/DatePicker/index.js
src/themes/five/src/components/UserFormDetails/index.js

story: https://app.asana.com/0/0/1204855423272300/f

[Fix] invalid date when there is not a birthdate, date picker max date

---

template/app.js

This reverts commit b6fb04729982ee2eb94e01e1319bedc00f53d4f1.

Revert "[ADD] effect to update hashkey (#1765)"

---

src/themes/five/src/components/PhoneAutocomplete/index.js

story: https://app.asana.com/0/1199511033583011/1204842492179974/f

[Feat] get phone number from url

---

src/themes/five/index.js

[FEAT] missing export

---

src/themes/five/src/components/Cart/index.js
src/themes/five/src/components/GiftCard/SendGiftCard/index.js

STORY: https://app.asana.com/0/1198717964402573/1204908336467994

[Fix] gift card feedback

---

src/themes/five/src/components/BusinessPreorder/styles.js
src/themes/five/src/components/ServiceForm/index.js

Story: https://app.asana.com/0/1200268243113852/1204917623640083

[Update]: professional

---

src/themes/five/src/components/Cart/index.js
src/themes/five/src/components/Checkout/index.js
src/themes/five/src/components/UserFormDetails/index.js
src/themes/five/src/components/UserFormDetails/styles.js

Story: https://app.asana.com/0/1200268243113852/1204729057889963

[Update]: guest checkout setting

---

src/themes/five/src/components/ServiceForm/index.js

Story: https://app.asana.com/0/1200268243113852/1204945188326233

[Update]: booking update

---

src/themes/five/src/components/ServiceForm/index.js

Story: https://app.asana.com/0/1200268243113852/1204945188326233

[Update]: booking feedback

---

src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js

Story: https://app.asana.com/0/0/1204972384557163/f

[FEAT] change

---

src/themes/five/src/components/GiftCard/GiftCardOrdersList/index.js
src/themes/five/src/components/GiftCard/GiftCardOrdersList/styles.js
src/themes/five/src/components/GiftCard/HorizontalGiftCardOrdersLayout/index.js
src/themes/five/src/components/GiftCard/HorizontalGiftCardOrdersLayout/styles.js
src/themes/five/src/components/GiftCard/SingleGiftCard/index.js
src/themes/five/src/components/GiftCard/SingleGiftCard/styles.js
src/themes/five/src/components/GiftCard/VerticalGiftCardOrdersLayout/index.js
src/themes/five/src/components/GiftCard/VerticalGiftCardOrdersLayout/styles.js
src/themes/five/src/components/MyOrders/index.js
src/themes/five/src/components/OrdersOption/index.js

STORY: https://app.asana.com/0/1198717964402573/1205003033267840

[Add] Gift card orders

---

src/themes/five/src/components/Checkout/index.js

STORY: https://app.asana.com/0/1198717964402573/1204981637490290

[Fix] driver tip require message for gift card

---

src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/ProductForm/index.js

STORY: https://app.asana.com/0/1198717964402573/1204992858436035

[Fix] Banner redirect issue

---

src/themes/five/src/components/BusinessItemAccordion/index.js
src/themes/five/src/components/BusinessItemAccordion/styles.js

Story: https://app.asana.com/0/1200268243113852/1205018225449483

[Update]: fix visual issue

---

src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js

story: https://app.asana.com/0/1199511033583011/1205086494554458/f

[Fix] web crash

---

src/themes/five/src/components/GiftCard/GiftCardOrdersList/index.js
src/themes/five/src/components/GiftCard/HorizontalGiftCardOrdersLayout/index.js
src/themes/five/src/components/GiftCard/SingleGiftCard/index.js
src/themes/five/src/components/GiftCard/SingleGiftCard/styles.js

STORY: https://app.asana.com/0/1198717964402573/1205041016994256

Feedback gift orders

---

src/themes/callcenterOriginal/src/components/UserDetails/index.js
src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js
src/themes/five/src/components/RenderProductsLayout/index.js
src/themes/five/src/components/UserDetails/index.js

Story: https://app.asana.com/0/1199511033583011/1205085769488519/f

[FEAT] fixes for callcenter

---

src/themes/five/src/components/BusinessBasicInformation/index.js

story: https://app.asana.com/0/1199511033583011/1205055751054925/f

[Update] advance settings

---

src/themes/five/src/components/ProductItemAccordion/index.js
src/themes/five/src/components/UserDetails/styles.js

story: https://app.asana.com/0/1199511033583011/1205096803165374/f

[Fix] fixes for website

---

src/themes/five/src/components/Header/index.js
src/themes/five/src/components/MomentControl/index.js

story: https://app.asana.com/0/1199511033583011/1205102089922592/f

[Fix] preorder schedule for single business

---

src/themes/five/src/components/BusinessController/index.js

story: https://app.asana.com/0/1199511033583011/1205146198376883/f

[Update] add the word discount in the offer ribbon

---

src/themes/five/src/components/BusinessController/index.js

story: https://app.asana.com/0/1199511033583011/1205146198376883/f

[Fix] validate when discount its 0

---

src/themes/five/src/components/BusinessesListing/layouts/OriginalBusinessesListing/index.js
src/themes/five/src/components/WebsocketStatus/index.js

story: https://app.asana.com/0/1199511033583011/1205172990143647/f

[Update] hide support link when white label module its enabled

---

src/themes/five/src/components/AddressList/index.js
src/themes/five/src/components/OrderDetails/index.js
src/themes/five/src/components/ProductItemAccordion/index.js

Story: https://app.asana.com/0/1200268243113852/1204981637490286

[Update]: add arrow icon

---

src/themes/five/src/components/BusinessProductsListing/index.js
src/themes/five/src/components/MyOrders/index.js
src/themes/five/src/components/OrdersOption/index.js
src/themes/five/src/components/PageBanner/index.js
src/themes/five/src/components/RenderProductsLayout/index.js

STORY: https://app.asana.com/0/1198717964402573/1205195151125083

[Fix] bugs

---

src/themes/five/src/components/WebsocketStatus/index.js

STORY: https://app.asana.com/0/1198717964402573/1205195578411811

[Update] language variable by white label module

---

src/themes/five/src/components/MomentControl/index.js

story: https://app.asana.com/0/1199511033583011/1205195578411822/f

[Fix] enable continue button for asap after select preorder

---

src/themes/callcenterOriginal/src/components/PhoneAutocomplete/index.js
src/themes/callcenterOriginal/src/components/PhoneAutocomplete/styles.js

story: https://app.asana.com/0/1199511033583011/1204842492179974/f

[Fix] fixes for callcenter feature: get phone from url

---

src/themes/six/src/components/SidebarMenu/index.js

story: https://app.asana.com/0/1199511033583011/1205338591845408/f

[Fix] elegant layout fixes

---

src/themes/six/src/components/Header/index.js
src/themes/six/src/components/SidebarMenu/index.js

story: https://app.asana.com/0/1199511033583011/1205338591845408/f

[Fix] signup issue in elegant layout

---

src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/ProductItemAccordion/index.js
src/themes/five/src/components/SingleProductCard/layouts/original/index.js
src/themes/five/src/components/UpsellingPage/index.js

Story: https://app.asana.com/0/1199511033583011/1205271159588662/f
Video: https://d.pr/v/pMPap3

[FEAT] dummy-logo-hide-theme

---

src/themes/callcenterOriginal/src/components/AddressForm/index.js
src/themes/callcenterOriginal/src/components/AddressList/index.js
src/themes/callcenterOriginal/src/components/Header/index.js
src/themes/callcenterOriginal/src/components/Orders/AddressForm/index.js

story: https://app.asana.com/0/1199511033583011/1205144809732696/f

[Fix] franchise filter

---

src/themes/callcenterOriginal/src/components/AddressForm/index.js

story: https://app.asana.com/0/1199511033583011/1205144809732696/f

[Fix] fallback icon for business in google maps

---

src/themes/five/src/components/BusinessProductsCategories/layouts/groceries/styles.js

Story: https://app.asana.com/0/1199511033583011/1205408286738006/f
Video: https://d.pr/v/7EUe8G

[FEAT] fix-design-product-categories

---

src/themes/five/src/components/SignUpDriver/layouts/NewSignUpDriver/index.js
src/themes/five/src/components/SignUpDriver/layouts/OldSignUpDriver/index.js
template/pages/SignUpDriver/index.js

story: https://app.asana.com/0/1199511033583011/1205399505612090/f

[Fix] error title

---

src/utils/index.js

sotry: https://app.asana.com/0/1199511033583011/1205598560486797/f

[Fix] show progress bar when finish by driver in pickup

---

src/themes/five/src/components/OrderDetails/OrderEta.js

Story: https://app.asana.com/0/1199511033583011/1205643777775849/f

[FEAT] fix-preorder-delivery-time

---

src/themes/five/src/components/OrderDetails/index.js

story: https://app.asana.com/0/1199511033583011/1205598560486797/f

[Fix] validate button for layouts

---

src/themes/five/src/components/Cart/index.js
src/themes/five/src/components/OrderDetails/OrderBillSection.js
src/themes/five/src/components/TaxInformation/index.js

Story: https://app.asana.com/0/0/1205646660407818/f
Video: https://d.pr/v/TN0JcE

[FEAT] delivery fee taxes

---

src/themes/callcenterOriginal/src/components/PhoneAutocomplete/index.js
template/config.js

Story: https://app.asana.com/0/0/1205674017702722/f

[FEAT] fix-map-franchise-filter

---

src/themes/five/src/components/HighestRated/index.js

story: https://app.asana.com/0/1199511033583011/1205660278710616/f

[Fix] preorder for highest rated business

---

src/themes/five/src/components/OrderDetails/index.js
src/themes/five/src/components/ServiceForm/index.js

story: https://app.asana.com/0/0/1205296368607789/f

[Fix] hide busy time

---

src/themes/five/src/components/Cart/index.js
src/themes/five/src/components/OrderDetails/OrderBillSection.js

Story: https://app.asana.com/0/1205349486814348/1205728971843396/f

[FEAT] cart-extra-value-checkprice

---

src/themes/callcenterOriginal/src/components/Orders/OrdersTable/index.js
src/themes/callcenterOriginal/src/components/Orders/OrdersTable/styles.js

Story: https://app.asana.com/0/0/1205806633088965/f

[FEAT] add agent column

---

src/themes/five/src/components/OrderDetails/index.js

Story: https://app.asana.com/0/1199511033583011/1205836171483992/f

[FEAT] fix custom order reviews

---

src/themes/five/src/components/OrderDetails/OrderBillSection.js

story: https://app.asana.com/0/1199511033583011/1205929150486792/f

[Fix] hide delivery fee on pickup

---

src/themes/five/src/components/BusinessProductsList/index.js

Story: https://app.asana.com/0/1164464536714178/1206251127870325/f

[FEAT] sort-products-by-rank

---

src/themes/five/src/components/OrderDetails/OrderHistory.js

Story: https://app.asana.com/0/1199511033583011/1206351585168283/f

fix-messages-shown-history-details

---

src/themes/five/src/components/OrderDetails/index.js

[FEAT] order-details-integration-id-date

[FEAT] order-details-integration-id-date

---

src/themes/five/src/components/OrderDetails/index.js

Story: https://app.asana.com/0/0/1206420816372376/f

[FEAT] change-integration-id-date

---

src/themes/five/src/components/OrderDetails/index.js

[FEAT] add label

---

src/themes/five/src/components/SignUpForm/index.js
src/themes/five/src/components/UserFormDetails/index.js

Story: https://app.asana.com/0/0/1206587082431499/f

[FEAT] add-config-phone-validation

---

src/themes/five/src/components/Checkout/index.js

Story: https://app.asana.com/0/0/1206648867971159/f

[FEAT] config-phone-lib-validation-checkout

---

src/themes/five/src/components/SignUpForm/index.js
src/themes/five/src/components/UserFormDetails/index.js

Story: https://app.asana.com/0/1199511033583011/1206558544547040/f

improvement-avoid-spaces-cellphone

---

src/themes/five/src/components/ProductItemAccordion/index.js

Story: https://app.asana.com/0/0/1206975426018069/f

[FEAT] fix-sort-suboptions

---

src/utils/index.js

Story: https://app.asana.com/0/1199511033583011/1206981293673908/f

[FEAT] fix-catering-bug

---

src/themes/five/src/components/SignUpForm/index.js

Story: https://app.asana.com/0/0/1207308892383290/f

[FEAT] fix-configs-validations

---

package.json
yarn.lock

Story: https://app.asana.com/0/0/1207592433611703/f

remove-sentry

---

src/themes/callcenterOriginal/src/components/AddressList/index.js

Story: https://app.asana.com/0/1164464536714178/1207872602286250/f

[FEAT] fix-add-address-redirect

---

src/themes/five/src/components/OrderDetails/index.js

Story: https://app.asana.com/0/1164464536714178/1208170942643763/f

feat: update validTrackingStatus array in OrderDetailsUI component

---

src/styles/Toast/index.js
src/themes/five/index.js
src/themes/five/src/components/Checkout/index.js
src/themes/five/src/components/InputPhoneNumber/index.js
src/themes/five/src/components/Modal/index.js
src/themes/five/src/components/PaymentOptionStripeLink/index.js
src/themes/five/src/components/PaymentOptionStripeLink/styles.js
src/themes/five/src/components/PaymentOptions/index.js

Story: https://app.asana.com/0/1164464536714178/1208468965897293/f

Feat: add stripe payment for callcenter

---

src/components/UpsellingPage/index.js
src/themes/five/src/components/UpsellingPage/index.js

Story: https://app.asana.com/0/1164464536714178/1208530725003388/f

Refactor: Add useSuggestiveUpselling flag to UpsellingPage component

---

src/themes/five/src/components/Checkout/index.js
src/themes/five/src/components/PaymentOptionStripeLink/index.js

Story: https://app.asana.com/0/0/1208612983397325/f

Refactor: Remove unused useEffect hook in Checkout component

---

src/themes/five/src/components/Checkout/index.js
src/themes/five/src/components/PaymentOptionStripeLink/index.js
src/themes/five/src/components/PaymentOptionStripeLink/styles.js

Story: https://app.asana.com/0/1164464536714178/1208602367363143/f

Add-configs-stripe-link

---

src/themes/five/src/components/PaymentOptionStripeLink/index.js
src/themes/five/src/components/PaymentOptionStripeLink/styles.js
src/utils/index.js

Story: https://app.asana.com/0/1164464536714178/1208628811507835/f

Refactor: Add loading state and URL link for Stripe Link payment option

---

src/themes/five/src/components/ProductForm/index.js
src/themes/five/src/components/UpsellingPage/index.js

Story: https://app.asana.com/0/1164464536714178/1208717999119422/f

Refactor: Improve optional chaining for product properties in ProductForm and UpsellingPage components

---

src/themes/callcenterOriginal/src/components/PhoneAutocomplete/index.js
src/themes/callcenterOriginal/src/components/SignUpForm/index.js
src/themes/callcenterOriginal/src/components/UserFormDetails/index.js

Story: https://app.asana.com/0/1164464536714178/1208532909628139/f

Refactor: Enhance error handling and validation messages in PhoneAutocomplete, SignUpForm, and UserFormDetails components

---

src/themes/five/src/components/BusinessProductsListing/index.js

Story: https://app.asana.com/0/0/1209108713827867/f

Refactor: Simplify product and category slug retrieval in BusinessProductsListing component

---

src/themes/five/src/components/Checkout/index.js

Story: https://app.asana.com/0/1164464536714178/1209119928344661/f

Refactor: Update driver tips field condition to include guest checkout option in Checkout component

---

src/themes/five/src/components/Checkout/index.js

Story: https://app.asana.com/0/1164464536714178/1209209284902443/f

Refactor: Add cartTotal prop to PaymentOptionStripeLink in Checkout component

---

src/themes/five/src/components/ProductOptionSubOption/index.js

Story: https://app.asana.com/0/1164464536714178/1209259258289778/f

Refactor: Enhance product option suboption logic for half and whole options
